<Project Sdk="Microsoft.NET.Sdk"><PropertyGroup><TargetFramework>net10.0</TargetFramework></PropertyGroup><ItemGroup><PackageReference Include="NAudio.Wasapi" Version="2.2.1" /></ItemGroup><ItemGroup><None Update="NAudio-LICENSE.txt" CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="PreserveNewest" TargetPath="licenses/NAudio-LICENSE.txt" /></ItemGroup></Project>
