<Project Sdk="Microsoft.NET.Sdk"><PropertyGroup><TargetFramework>net10.0</TargetFramework></PropertyGroup><ItemGroup><PackageReference Include="OpenCvSharp4" Version="4.13.0.20260627" /></ItemGroup><ItemGroup Condition="$([MSBuild]::IsOSPlatform('Windows')) Or '$(RuntimeIdentifier)' == 'win-x64'"><PackageReference Include="OpenCvSharp4.runtime.win" Version="4.13.0.20260627" /></ItemGroup><ItemGroup><None Update="licenses/*" CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="PreserveNewest" TargetPath="licenses/%(Filename)%(Extension)" /></ItemGroup></Project>
