import {useEffect,useRef,useState} from 'react';
import QRCode from 'qrcode';
import {request,type Snapshot} from '../api';
import {PhoneBridge,initialBridgeView,type PhoneSnapshot} from './PhoneBridge';
import {hasCapability} from './bridgeProtocol';
import './phone-settings.css';

type GatewayConfig={enabled:boolean;phoneOrigin:string|null;setupUrl:string|null;fingerprint:string|null;expiresAt:string|null;httpCheckUrl?:string|null;httpsCheckUrl?:string|null;addresses:{address:string;name:string}[]};

export default function PhoneSensorSettings({snapshot,onSession,t,onExperiment,onLibrary,embedded=false,onConnectionChange}:{snapshot:Snapshot|null;onSession:(s:Snapshot)=>void;t:(zh:string,en:string)=>string;onExperiment?:()=>void;onLibrary?:()=>void;embedded?:boolean;onConnectionChange?:(state:{connected:boolean;connecting:boolean;bound:boolean})=>void}){
 const [view,setView]=useState(initialBridgeView),[config,setConfig]=useState<GatewayConfig|null>(null),[address,setAddress]=useState(''),[gatewayBusy,setGatewayBusy]=useState(false),[setupQr,setSetupQr]=useState(''),[checkQr,setCheckQr]=useState(''),[configError,setConfigError]=useState(''),[qr,setQr]=useState(''),[selected,setSelected]=useState(''),[binding,setBinding]=useState(false);
 const origin=config?.phoneOrigin;
 const callback=useRef(onSession);callback.current=onSession;
 const [bridge]=useState(()=>new PhoneBridge(setView,s=>callback.current(s)));
 useEffect(()=>{let live=true;request<GatewayConfig>('phone/config').then(c=>{if(live){setConfig(c);setAddress(c.addresses[0]?.address??'');}}).catch(e=>{if(live)setConfigError(String(e));});return()=>{live=false;void bridge.disconnect();};},[bridge]);
 useEffect(()=>bridge.setSnapshot(snapshot as PhoneSnapshot|null),[bridge,snapshot]);
 useEffect(()=>{let live=true;setQr('');if(view.link)void QRCode.toDataURL(view.link,{width:280,margin:4,errorCorrectionLevel:'M'}).then(url=>{if(live)setQr(url);}).catch(()=>{if(live)setConfigError(t('二维码生成失败，可复制连接链接。','QR generation failed. Copy the connection link instead.'));});return()=>{live=false;};},[view.link]);
 useEffect(()=>{let live=true;setSetupQr('');if(config?.setupUrl)void QRCode.toDataURL(config.setupUrl,{width:240,margin:4}).then(url=>{if(live)setSetupQr(url);});return()=>{live=false;};},[config?.setupUrl]);
 useEffect(()=>{let live=true;setCheckQr('');if(config?.httpsCheckUrl)void QRCode.toDataURL(config.httpsCheckUrl,{width:240,margin:4}).then(url=>{if(live)setCheckQr(url);});return()=>{live=false;};},[config?.httpsCheckUrl]);
 async function gateway(enable:boolean){setGatewayBusy(true);setConfigError('');try{await bridge.disconnect();const next=await request<GatewayConfig>(enable?'phone/enable':'phone/disable',enable?{address}:{});setConfig(next);if(enable&&next.phoneOrigin)await bridge.connect(next.phoneOrigin);}catch(e){setConfigError(e instanceof Error?e.message:String(e));}finally{setGatewayBusy(false);}}
 const inputs=(snapshot?.inputs??[]).filter(i=>hasCapability(view.capabilities,i.type==='sensor'?i.sensorType??'':i.type));
 const bound=view.bound;
 const step=!snapshot?.id?1:!view.connected?2:!bound?3:4;
 useEffect(()=>onConnectionChange?.({connected:view.connected,connecting:view.connecting,bound:!!bound}),[view.connected,view.connecting,!!bound,onConnectionChange]);
 useEffect(()=>{setSelected('');},[snapshot?.id]);
 useEffect(()=>{if(inputs.length===1)setSelected(String(inputs[0].index));else if(!inputs.some(i=>String(i.index)===selected))setSelected('');},[inputs.map(i=>i.index).join(','),selected]);
 return <section className="phone-settings">
  {!embedded&&<><p className="eyebrow">PHONE SENSORS</p><h1>{t('实验准备 · 手机传感器','Experiment setup · Phone sensors')}</h1></>}

  <ol className="phone-steps" aria-label={t('连接步骤','Connection steps')}>{[t('选择实验','Choose experiment'),t('连接手机','Connect phone'),t('授权并绑定','Enable & bind'),t('进入测量','Enter measurement')].map((label,index)=><li key={label} className={step===index+1?'current':step>index+1?'complete':''} aria-current={step===index+1?'step':undefined}><span>{index+1}</span>{label}</li>)}</ol>
  <div className="panel phone-experiment"><div><p className="eyebrow">{snapshot?.id?t('已选择的实验','SELECTED EXPERIMENT'):t('连接前准备','PHONE PREPARATION')}</p><h2>{snapshot?.id?snapshot.title:t('尚未选择实验','No experiment selected')}</h2><p>{snapshot?.id?(view.connected?t('沿用已连接的手机，启用对应传感器后绑定。','Reuse your connected phone; enable and bind its sensor.'):t('连接并绑定后，即可进入测量。','Connect and bind, then enter measurement.')):t('可先连接手机；选择实验后再绑定输入。','Connect now and bind an input after choosing an experiment.')}</p></div>{onLibrary&&<button onClick={onLibrary}>{snapshot?.id?t('更换实验','Choose another experiment'):t('前往实验库','Open experiment library')}</button>}</div>

  {(configError||view.error)&&<div className="alert error" role="alert">{view.error||configError}</div>}
  {!config?.enabled&&<div className="phone-enable"><label>{t('电脑连接手机所在网络的地址','Computer address on the phone network')}<select value={address} onChange={e=>setAddress(e.target.value)}>{config?.addresses.map(a=><option key={a.address} value={a.address}>{a.name} · {a.address}</option>)}</select></label><button className="primary" disabled={gatewayBusy||!address} onClick={()=>void gateway(true)}>{gatewayBusy?t('正在启用…','Enabling…'):t('启用并显示连接二维码','Enable & show connection QR')}</button>{config&&!config.addresses.length&&<p>{t('未发现可用局域网 IPv4 地址，请先连接 Wi-Fi 或有线网络。','No local IPv4 address found. Connect to Wi-Fi or Ethernet first.')}</p>}</div>}

  {config?.enabled&&<div className="phone-connection-row"><p className={view.connected?'phone-connected':'muted'} role="status">{view.status}</p><div className="row">{!view.connected&&!view.pendingName&&<button className={view.link?'':'primary'} disabled={!origin||binding} onClick={()=>origin&&void bridge.connect(origin)}>{view.link?t('刷新二维码','Refresh QR'):view.connecting?t('重新配对','Retry pairing'):t('生成连接二维码','Show connection QR')}</button>}{(view.connecting||view.connected)&&<button className="text-button" onClick={()=>void bridge.disconnect()}>{t('断开','Disconnect')}</button>}</div></div>}
  {view.link&&<div className="panel phone-pair"><div>{qr?<img src={qr} width={280} height={280} alt={t('手机配对二维码','Phone pairing QR code')}/>:<p>{t('正在生成二维码…','Generating QR…')}</p>}</div><div><h2>{t('用手机系统相机扫描','Scan with your phone camera')}</h2><p>{t('在手机系统浏览器打开，点击“连接 Windows”，然后在电脑确认接入。','Open in your phone’s system browser, tap Connect Windows, then accept the connection on this computer.')}</p><p>{t('过期时间','Expires')}: {new Date(view.expiresAt).toLocaleTimeString()}</p><button onClick={()=>void navigator.clipboard.writeText(view.link).catch(()=>setConfigError(t('复制失败，请直接扫码。','Could not copy. Please scan the code.')))}>{t('复制临时连接链接','Copy temporary link')}</button></div></div>}
  {view.pendingName&&<div className="panel"><h2>{t('确认接入手机','Confirm phone connection')}</h2><p>{view.pendingName}</p><p>{t('仅接纳你刚刚扫码的手机。','Accept only the phone you just scanned.')}</p><div className="row"><button className="primary" onClick={()=>bridge.confirm(true)}>{t('允许连接','Accept')}</button><button onClick={()=>bridge.confirm(false)}>{t('拒绝','Reject')}</button></div></div>}
  {view.connected&&<div className="panel"><h2>{t('3 · 授权并绑定输入','3 · Enable and bind a sensor')}</h2><p className="phone-connected">{view.name||t('手机已连接','Phone connected')}</p><p>{t('在手机上点击对应授权按钮，再将可用传感器绑定到实验。','Enable a sensor on your phone, then bind it to an experiment.')}</p><div className="phone-capabilities">{[['accelerometer',t('含重力加速度','Acceleration')],['gyroscope',t('角速度','Angular velocity')],['linear_acceleration',t('线性加速度','Linear acceleration')],['audio',t('麦克风','Microphone')],['camera',t('摄像头','Camera')]].map(([kind,label])=><span className={hasCapability(view.capabilities,kind)?'available':''} key={kind}>{label} · {hasCapability(view.capabilities,kind)?t('可用','Available'):t('未启用','Not enabled')}</span>)}</div>
   {bound?<><div className="phone-ready"><h3>{t('4 · 输入已绑定，前往实验测量','4 · Sensor bound — open your experiment')}</h3><p>{t('已绑定实验输入','Bound experiment input')}: {snapshot?.inputs?.find(i=>i.index===bound.inputIndex)?.name||bound.kind}</p><p>{snapshot?.status==='running'?t('正在测量。返回当前实验查看曲线、暂停或导出数据。','Measuring. Return to the experiment to view graphs, pause or export.'):snapshot?.canStart?t('输入已就绪。点击下方按钮进入实验，再点击“开始”采集。','Input ready. Enter the experiment below, then press Start to measure.'):t('正在确认输入数据；进入实验后可查看就绪状态。','Confirming input data. Enter the experiment to check readiness.')}</p>{onExperiment&&<button className="primary" onClick={onExperiment}>{t('进入实验测量','Enter experiment measurement')}</button>}</div><button disabled={binding} onClick={()=>{setBinding(true);void bridge.unbind().finally(()=>setBinding(false));}}>{t('停止并解除绑定','Stop & unbind')}</button></>:<><label>{t('实验输入','Experiment input')}<select value={selected} onChange={e=>setSelected(e.target.value)}><option value="">{t('请选择…','Select…')}</option>{inputs.map(i=><option key={i.index} value={i.index}>{i.name||i.type}</option>)}</select></label><button className="primary" disabled={binding||!snapshot?.id||snapshot.status==='running'||selected===''||!inputs.some(i=>i.index===Number(selected))} onClick={()=>{setBinding(true);void bridge.bind(Number(selected)).finally(()=>setBinding(false));}}>{binding?t('正在绑定…','Binding…'):t('绑定到所选实验','Bind to selected experiment')}</button>{!inputs.length&&<p className="muted">{snapshot?.id?t('当前实验没有已授权的匹配输入。请先在手机授权或切换实验。','No authorized matching input. Enable a phone sensor or choose another experiment.'):t('手机已准备好；前往实验库选择一个实验即可继续绑定，无需重复扫码。','Phone ready. Choose an experiment from the library to bind its input; no need to scan again.')}</p>}</>}
   <details><summary>{t('连接与测量信息','Connection & measurement details')}</summary><p>{t('设备直连，无云端数据中继','Direct connection; no cloud data relay')} · RTT {view.rtt??'—'} ms · {t('服务已接受批次','Accepted batches')} {view.accepted}</p><p>{t('运动时间按首个样本对齐本段实验；相机时间为服务接收时刻。此验证版不提供跨传感器精密同步或标定测量。','Motion time is aligned to the first sample of the segment; camera time is service reception time. This prototype does not provide precision synchronization or calibrated measurements.')}</p><p>{t('运动实验目前支持默认采样速率；显式指定速率、平均或校准属性会提示不支持。','Motion supports default sample rates; explicit rate, averaging or calibration attributes are currently rejected.')}</p></details>
  </div>}
  <p className="phone-footnote">{t('无需互联网 · 首版同时绑定一个输入 · 采集时保持手机页面在前台','No internet needed · One input at a time · Keep the phone page in the foreground')}</p>
  {config?.enabled&&<details className="settings-advanced phone-advanced"><summary>{t('浏览器打不开页面或无法授权？','Page or permission problems?')}</summary><p>{t('首次打开本地 HTTPS，浏览器可能显示证书提示。核对地址是这台电脑后，若浏览器提供继续访问选项，可先尝试进入页面再授权；具体手机是否可用需要实测。','Local HTTPS may show a certificate prompt. Verify the address belongs to this computer; if the browser offers a continue option, try entering the page and granting permission. Phone compatibility must be tested.')}</p><p>{t('用下面的独立页面检查浏览器接口和真实传感器数据，不需要先完成配对。','Use this independent page to check browser APIs and actual sensor data without pairing.')}</p>{checkQr&&<img src={checkQr} width={240} height={240} alt={t('浏览器传感器验证二维码','Browser sensor check QR')}/>}<p><a href={config.httpsCheckUrl??undefined} target="_blank" rel="noreferrer">HTTPS {t('验证页','sensor check')}</a> · <a href={config.httpCheckUrl??undefined} target="_blank" rel="noreferrer">HTTP {t('对照页','comparison')}</a></p><details><summary>{t('兼容选项：手动信任本机证书','Compatibility option: trust the local certificate')}</summary><p>{t('仅在目标浏览器确实需要时使用。扫描引导码安装并信任本机证书，核对下方 SHA-256 指纹；不作为默认必经步骤。','Use only if the target browser needs it. Scan the guide to install and trust the local certificate, checking the SHA-256 fingerprint below. This is not a required default step.')}</p>{setupQr&&<img src={setupQr} width={240} height={240} alt={t('可选证书引导二维码','Optional certificate guide QR')}/>}<code>{config.fingerprint}</code></details><button disabled={gatewayBusy} onClick={()=>void gateway(false)}>{t('停止并关闭局域网入口','Stop & disable LAN entry')}</button></details>}
 </section>;
}
