export type Attributes = Record<string,string>;
export type Port = {buffer:string;attributes:Attributes};
export type Element = {id:string;type:string;attributes:Attributes;text?:string;inputs:Port[];outputs:Port[];children?:Node[]};
export type Node = {name?:string;type?:string;text?:string;attributes:Attributes;children?:Node[]};
export type Experiment = {id:string;title:string;category:string;description:string;source:string;formatVersion:string;requirements:string[];isLink:boolean;loadError?:string};
export type Snapshot = {browserAudioOutput?:{streamId:string;outputIndex:number;sampleRate:number;channels?:number}[];browserMedia?:{captureId:string;kind:string;inputIndex:number;sampleRate?:number;width?:number;height?:number}[];id?:string;title:string;status:string;experimentTime:number;cycle:number;canStart:boolean;issues:string[];views:{label:string;elements:Element[]}[];buffers:Record<string,(number|null)[]>;clearGroups:string[];inputs?:{index:number;type:string;name?:string;sensorType?:string;outputs:string[]}[];inputBindings?:unknown[];outputs?:{index:number;type:string;inputs?:string[]}[];outputBindings?:{id:string;connectionId:string;triggerId?:string;sendOnEachAnalysis?:boolean;outputIndex?:number}[];revision?:number;displayLimit?:number;bufferLengths?:Record<string,number>;timeMappings?:{event:string;experimentTime:number;systemTime:string}[];dataOrigin?:string;network?:{id:string;service:string;address:string;error?:string;completed:number;connected?:boolean}[];networkDiagnostics?:string[];droppedNetworkResponses?:number;error?:string};
export type Device = {id:string;name:string;kind:string};
export type Devices = {items:Device[];connections?:{connectionId?:string;id?:string;status?:string;device?:Device}[];capabilities:{kind:string;status:string;reason:string}[]};
let tokenPromise:Promise<string>|undefined;
async function token(){return tokenPromise??=(fetch('/api/v1/bootstrap').then(async r=>{if(!r.ok)throw new Error('Bootstrap failed');return (await r.json()).token as string;}).catch(e=>{tokenPromise=undefined;throw e;}));}
export async function request<T>(path:string, body?:unknown):Promise<T>{
 const headers:Record<string,string>={'X-Phyphox-Token':await token()};
 if(body!==undefined){headers['X-Phyphox-Client']='browser';headers['X-Phyphox-Token']=await token();if(!(body instanceof FormData))headers['Content-Type']='application/json';}
 const r=await fetch('/api/v1/'+path,{method:body===undefined?'GET':'POST',headers,body:body===undefined?undefined:body instanceof FormData?body:JSON.stringify(body)});
 if(!r.ok){if(r.status===401||r.status===403)tokenPromise=undefined;const e=await r.json().catch(()=>({error:r.statusText}));throw Object.assign(new Error(e.error||r.statusText),{status:r.status});}
 return r.json();
}
export async function downloadBlob(path:string):Promise<Blob>{const r=await fetch('/api/v1/'+path,{headers:{'X-Phyphox-Token':await token()}});if(!r.ok){if(r.status===401||r.status===403)tokenPromise=undefined;const e=await r.json().catch(()=>({error:r.statusText}));throw Object.assign(new Error(e.error||r.statusText),{status:r.status});}return r.blob();}
export async function downloadFile(path:string,body?:unknown):Promise<{blob:Blob;filename?:string}>{const headers:Record<string,string>={'X-Phyphox-Token':await token()};if(body!==undefined){headers['X-Phyphox-Client']='browser';headers['Content-Type']='application/json';}const r=await fetch('/api/v1/'+path,{method:body===undefined?'GET':'POST',headers,body:body===undefined?undefined:JSON.stringify(body)});if(!r.ok){if(r.status===401||r.status===403)tokenPromise=undefined;const e=await r.json().catch(()=>({error:r.statusText}));throw Object.assign(new Error(e.error||r.statusText),{status:r.status});}const header=r.headers.get('content-disposition')||'',encoded=/filename\*=UTF-8''([^;]+)/i.exec(header)?.[1],plain=/filename="?([^";]+)"?/i.exec(header)?.[1];return {blob:await r.blob(),filename:encoded?decodeURIComponent(encoded):plain};}
