import {useEffect,useRef,useState,type ReactNode} from 'react';
import {request,downloadBlob,downloadFile,type Devices,type Element,type Experiment,type Snapshot} from './api';
import Graph from './Graph';
import DevicePanel from './DevicePanel';
import StoragePanel from './StoragePanel';
import MediaPanel from './MediaPanel';
import BrowserMediaPanel from './BrowserMediaPanel';
import BrowserSpeakerPanel from './BrowserSpeakerPanel';
import {mappedText} from './viewData';

type Page = 'library'|'experiment'|'devices'|'storage'|'media';
type IconName = 'library'|'wave'|'device'|'folder'|'audio'|'play'|'pause'|'back'|'clear'|'more'|'plus'|'search'|'arrow'|'help'|'save'|'sun'|'moon'|'close'|'sensor'|'camera';
function Icon({name,size=20}:{name:IconName;size?:number}){
 const paths:Record<IconName,ReactNode>={
  library:<><rect x="3" y="3" width="7" height="7" rx="1"/><rect x="14" y="3" width="7" height="7" rx="1"/><rect x="3" y="14" width="7" height="7" rx="1"/><rect x="14" y="14" width="7" height="7" rx="1"/></>,
  wave:<path d="M2 12h3l2-7 4 14 3-14 3 11 2-4h3"/>,device:<><rect x="6" y="3" width="12" height="18" rx="3"/><path d="M9 7h6M10 17h4"/></>,
  folder:<path d="M3 6a2 2 0 0 1 2-2h5l2 3h7a2 2 0 0 1 2 2v10a1 1 0 0 1-1 1H4a1 1 0 0 1-1-1Z"/>,
  audio:<><rect x="9" y="2" width="6" height="13" rx="3"/><path d="M5 10v2a7 7 0 0 0 14 0v-2M12 19v3M8 22h8"/></>,
  play:<path d="m8 4 12 8-12 8Z"/>,pause:<><path d="M8 4v16M16 4v16" strokeWidth="4"/></>,back:<path d="m14 5-7 7 7 7M7 12h14"/>,
  clear:<><path d="M3 6h18M9 6V3h6v3M5 6l1 15h12l1-15M10 10v7M14 10v7"/></>,more:<><circle cx="5" cy="12" r="1"/><circle cx="12" cy="12" r="1"/><circle cx="19" cy="12" r="1"/></>,
  plus:<path d="M12 4v16M4 12h16"/>,search:<><circle cx="10" cy="10" r="6"/><path d="m15 15 6 6"/></>,arrow:<path d="m9 5 7 7-7 7"/>,
  help:<><circle cx="12" cy="12" r="9"/><path d="M9 9a3 3 0 0 1 6 0c0 2-3 2-3 5M12 17h.01"/></>,save:<><path d="M12 3v12m-5-5 5 5 5-5M4 16v5h16v-5"/></>,
  sun:<><circle cx="12" cy="12" r="4"/><path d="M12 1v2m0 18v2M1 12h2m18 0h2M4 4l2 2m12 12 2 2M4 20l2-2M18 6l2-2"/></>,moon:<path d="M20 15A9 9 0 0 1 9 4a9 9 0 1 0 11 11Z"/>,close:<path d="m6 6 12 12M6 18 18 6"/>,
  sensor:<><circle cx="12" cy="12" r="3"/><path d="M12 2v5m0 10v5M2 12h5m10 0h5M5 5l3 3m8 8 3 3M5 19l3-3M16 8l3-3"/></>,camera:<><rect x="3" y="6" width="18" height="14" rx="2"/><path d="m8 6 2-3h4l2 3"/><circle cx="12" cy="13" r="4"/></>
 };
 return <svg width={size} height={size} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.7" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true">{paths[name]}</svg>;
}
function Dialog({title,onClose,children}:{title:string;onClose:()=>void;children:ReactNode}){
 const ref=useRef<HTMLDialogElement>(null);
 useEffect(()=>{ref.current?.showModal();},[]);
 return <dialog ref={ref} className="app-dialog" onCancel={e=>{e.preventDefault();onClose();}} aria-labelledby="dialog-title"><div className="dialog-heading"><h2 id="dialog-title">{title}</h2><button className="icon-button" aria-label="关闭 / Close" onClick={onClose}><Icon name="close"/></button></div>{children}</dialog>;
}
export default function App(){
 const [lang,setLang]=useState<'zh'|'en'>(()=>localStorage.getItem('language')==='en'?'en':'zh');
 const t=(zh:string,en:string)=>lang==='zh'?zh:en;
 const [mediaActivity,setMediaActivity]=useState({microphone:false,camera:false}),[speakerActive,setSpeakerActive]=useState(false);
 const [light,setLight]=useState(()=>localStorage.getItem('theme')==='light');
 const [library,setLibrary]=useState<Experiment[]>([]),[session,setSession]=useState<Snapshot|null>(null),[devices,setDevices]=useState<Devices|null>(null);
 const [search,setSearch]=useState(''),[source,setSource]=useState('all'),[tab,setTab]=useState(0),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[page,setPage]=useState<Page>('library'),[online,setOnline]=useState(false);
 const [dialog,setDialog]=useState<'help'|'about'|'save'|'clear'|null>(null),[pending,setPending]=useState<Experiment|null>(null),[clearGroups,setClearGroups]=useState<string[]>([]);
 const actionQueue=useRef<Promise<unknown>>(Promise.resolve()),pendingActions=useRef(0);
 useEffect(()=>{document.documentElement.dataset.theme=light?'light':'dark';localStorage.setItem('theme',light?'light':'dark');},[light]);
 useEffect(()=>{document.documentElement.lang=lang==='zh'?'zh-CN':'en';localStorage.setItem('language',lang);},[lang]);
 useEffect(()=>{setTab(0);},[session?.id]);
 useEffect(()=>{setTab(old=>Math.min(old,Math.max(0,(session?.views?.length||1)-1)));},[session?.views?.length]);
 async function refreshLibrary(){const r=await request<{items:Experiment[]}>('library');setLibrary(r.items);}
 function receiveSession(next:Snapshot){setSession(previous=>(previous?.revision??-1)>(next.revision??0)?previous:next);}
 useEffect(()=>{let cancelled=false,timer:ReturnType<typeof setTimeout>;async function poll(){let delay=1000;try{const next=await request<Snapshot>('session');if(!cancelled){receiveSession(next);setOnline(true);delay=next.status?.toLowerCase()==='running'?150:1000;}}catch(e){if(!cancelled){setOnline(false);setSession(null);setDialog(null);setPending(null);setError(String(e));}}if(!cancelled)timer=setTimeout(poll,delay);}poll();return()=>{cancelled=true;clearTimeout(timer);};},[]);
 useEffect(()=>{if(online){setError('');refreshLibrary().catch(e=>setError(String(e)));request<Devices>('devices').then(setDevices).catch(e=>setError(String(e)));}},[online]);
 function action(fn:()=>Promise<void>){
  pendingActions.current++;setBusy(true);
  const work=actionQueue.current.then(async()=>{setError('');try{await fn();return true;}catch(e){setError(e instanceof Error?e.message:String(e));return false;}finally{pendingActions.current--;if(pendingActions.current===0)setBusy(false);}});
  actionQueue.current=work;return work;
 }
 async function command(command:string,extra:Record<string,unknown>={}){return action(async()=>receiveSession(await request<Snapshot>('session/commands',{command,requestId:crypto.randomUUID(),...extra})));}
 const setValue=(buffer:string,value:number)=>{if(Number.isFinite(value))void command('set',{buffer,values:[value]});};
 const running=session?.status?.toLowerCase()==='running',current=library.find(i=>i.id===session?.id);
 const status=session?.status?.toLowerCase()||'';
 const setupIssues=session?.issues?.filter(issue=>issue!==session.error)||[];
 const needsSetup=!!session?.id&&!running&&!session.canStart&&setupIssues.length>0;
 const statusLabel=session?.error?t('运行中断','Interrupted'):needsSetup?t('需要配置','Needs setup'):({running:t('测量中','Measuring'),paused:t('已暂停','Paused'),stopped:t('已停止','Stopped'),ready:t('准备就绪','Ready'),faulted:t('运行中断','Interrupted'),empty:t('尚未选择实验','No experiment')})[status]||session?.status;
 const hasData=!!session?.id&&(session.cycle>0||Object.values(session.buffers||{}).some(b=>b.length>0));
 const filtered=library.filter(i=>(source==='all'||i.source===source)&&`${i.title} ${i.category} ${i.description}`.toLowerCase().includes(search.trim().toLowerCase()));
 const categories=[...new Set(filtered.map(i=>i.category||t('自定义实验','Custom experiments')))].sort((a,b)=>{const rank=(v:string)=>/^(Raw Sensors|原始传感器)$/.test(v)?0:1;return rank(a)-rank(b)||a.localeCompare(b,lang==='zh'?'zh-CN':'en');});
 const firstExperiment=library.find(i=>i.source==='sample'&&/公式|formula/i.test(i.title));
 const sourceLabel=(value:string)=>value==='official'?t('官方实验','Official'):value==='sample'?t('入门与示例','Examples'):t('我的实验','Imported');
 function inputLabel(requirements:string[]){
  const names=requirements.map(r=>r.includes('bluetooth')?'BLE':r.includes('audio')?t('音频','Audio'):r.includes('camera')||r.includes('depth')?t('摄像头','Camera'):r.includes('sensor')?t('传感器','Sensors'):r.includes('location')?t('定位','Location'):r.startsWith('network:')?t('网络','Network'):r.includes('serial')?'USB':r);
  return [...new Set(names)].join(' · ')||t('计算与交互','Calculation & controls');
 }
 function itemIcon(item:Experiment):IconName{const r=item.requirements.join();return /audio/.test(r)?'audio':/camera|depth/.test(r)?'camera':/bluetooth|serial/.test(r)?'device':/sensor|location/.test(r)?'sensor':'wave';}
 async function load(item:Experiment,save=false){
  await action(async()=>{if(save)await request('snapshots/save',{});receiveSession(await request<Snapshot>('session/load',{id:item.id}));setTab(0);setPage('experiment');setPending(null);setNotice(save?t('上一实验已保存，可在“数据与回放”中恢复。','Previous experiment saved. Restore it from Data & replay.'):'');});
 }
 function openExperiment(item:Experiment){if(item.id===session?.id){setPage('experiment');return;}if(session?.id&&(running||hasData)){setPending(item);return;}void load(item);}
 async function download(format:string){await action(async()=>{const {blob,filename}=await downloadFile(`exports?format=${format}`);const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=filename||`experiment.${format==='state'?'phyphox':format}`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);setNotice(t('已交给浏览器下载，请查看下载列表。','Download started. Check your browser downloads.'));setDialog(null);});}
 async function saveLocal(){await action(async()=>{await request('snapshots/save',{});setNotice(t('已保存到本机。可在“数据与回放”中恢复本次实验。','Saved locally. Restore this experiment from Data & replay.'));setDialog(null);});}
 function navigate(next:Page){setPage(next);setNotice('');if(next==='devices')void action(async()=>setDevices(await request<Devices>('devices')));}
 const nav:{page:Page;icon:IconName;label:string}[]=[{page:'library',icon:'library',label:t('实验库','Experiments')},{page:'experiment',icon:'wave',label:t('当前实验','Current experiment')},{page:'devices',icon:'device',label:t('连接设备','Connect devices')},{page:'storage',icon:'folder',label:t('数据与回放','Data & replay')},{page:'media',icon:'audio',label:t('音频与摄像头','Audio & camera')}];
 return <>
  <header className="app-header"><a className="brand" href="#" onClick={e=>{e.preventDefault();navigate('library');}}><span className="brand-icon"><Icon name="wave" size={30}/></span><span>phy<span className="brand-orange">phox</span><small>{t('Windows 实验工作台','Windows experiment workspace')}</small></span></a><div className="header-actions">{(mediaActivity.microphone||mediaActivity.camera||speakerActive)&&<button className="media-active" onClick={()=>navigate('media')} title={t('管理浏览器设备与停止播放','Manage browser devices and stop playback')}><i className="live-dot"/>{[mediaActivity.microphone?t('麦克风已启用','Microphone enabled'):'',mediaActivity.camera?t('相机已启用','Camera enabled'):'',speakerActive?t('扬声器已启用','Speaker enabled'):''].filter(Boolean).join(' · ')}</button>}<span className={'connection '+(online?'connected':'')}>{online?t('本地服务已连接','Local service connected'):t('等待本地服务','Waiting for local service')}</span><button className="icon-button" onClick={()=>setDialog('help')} title={t('使用帮助','How to use')} aria-label={t('使用帮助','How to use')}><Icon name="help"/></button><button className="language-button" onClick={()=>setLang(lang==='zh'?'en':'zh')}>{lang==='zh'?'EN':'中文'}</button><button className="icon-button" onClick={()=>setLight(!light)} title={t('切换主题','Toggle theme')} aria-label={t('切换主题','Toggle theme')}><Icon name={light?'moon':'sun'}/></button></div></header>
  <div className="layout"><aside className="app-sidebar"><p className="nav-caption">{t('实验工作台','WORKSPACE')}</p><nav aria-label={t('主导航','Main navigation')}>{nav.map(n=><button key={n.page} className={page===n.page?'active':''} aria-current={page===n.page?'page':undefined} onClick={()=>navigate(n.page)}><Icon name={n.icon}/><span>{n.label}</span>{n.page==='experiment'&&running&&<i className="live-dot"/>}</button>)}</nav>{session?.id&&<button className="session-shortcut" onClick={()=>navigate('experiment')}><span className="muted">{t('已打开的实验','OPEN EXPERIMENT')}</span><strong>{session.title}</strong><span className="session-shortcut-status">{running&&<i className="live-dot"/>}{statusLabel}<Icon name="arrow" size={14}/></span></button>}<div className="sidebar-note"><span className="offline-label"><i/>{t('核心实验可离线使用','Offline experiment workspace')}</span><span>{t('Windows 移植开发版','Windows development port')}</span><button className="text-button" onClick={()=>setDialog('help')}>{t('第一次使用？','Getting started')} <Icon name="arrow" size={13}/></button></div></aside>
  <main>
   {error&&<div role="alert" className="alert error"><span>{error}</span><button className="icon-button" aria-label={t('关闭错误提示','Dismiss error')} onClick={()=>setError('')}><Icon name="close" size={16}/></button></div>}
   {notice&&<div role="status" className="alert success"><span>{notice}</span><button className="icon-button" aria-label={t('关闭提示','Dismiss notification')} onClick={()=>setNotice('')}><Icon name="close" size={16}/></button></div>}
   {page==='library'&&<>
    <div className="page-heading"><div><p className="eyebrow">EXPERIMENTS</p><h1>{t('实验库','Experiments')}</h1><p className="muted">{t('选择或导入一个实验。','Choose or import an experiment.')}</p></div><label className={'button primary '+(busy?'disabled':'')} tabIndex={busy?-1:0} onKeyDown={e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();e.currentTarget.querySelector('input')?.click();}}}><Icon name="plus"/>{t('导入实验','Import experiment')}<input type="file" accept=".phyphox,.zip" disabled={busy} hidden onChange={e=>{const file=e.target.files?.[0];if(file)void action(async()=>{const data=new FormData();data.append('file',file);await request('library/import',data);await refreshLibrary();setSource('user');setSearch('');setNotice(t('实验已添加到“我的实验”。','Experiment added to Imported.'));});e.target.value='';}}/></label></div>
    <div className="welcome-strip"><div className="welcome-symbol"><Icon name="wave" size={30}/></div><div><h2>{t('第一次使用？','Getting started')}</h2><p>{t('先试试公式计算，无需连接设备。','Try a formula experiment. No equipment needed.')}</p></div><button onClick={()=>firstExperiment?openExperiment(firstExperiment):setDialog('help')}>{t('试试公式实验','Try a formula')}<Icon name="arrow" size={16}/></button></div>
    <div className="library-tools"><div className="source-tabs" role="group" aria-label={t('实验来源','Experiment source')}>{['all','official','sample','user'].map(s=><button key={s} aria-pressed={source===s} className={source===s?'active':''} onClick={()=>setSource(s)}>{s==='all'?t('全部实验','All experiments'):sourceLabel(s)}<span>{library.filter(i=>s==='all'||i.source===s).length}</span></button>)}</div><label className="search-field"><Icon name="search" size={18}/><input type="search" value={search} onChange={e=>setSearch(e.target.value)} aria-label={t('搜索实验','Search experiments')} placeholder={t('搜索实验、分类…','Search experiments…')}/></label></div>
    <div className="library-groups">{categories.map(category=><section className="experiment-group" key={category}><div className="category-heading"><h2>{category}</h2><span>{filtered.filter(i=>(i.category||t('自定义实验','Custom experiments'))===category).length}</span></div><div className="experiment-list">{filtered.filter(i=>(i.category||t('自定义实验','Custom experiments'))===category).map(item=><button className="experiment-row" key={item.id} disabled={busy||!online||!!item.loadError||item.isLink} title={item.loadError||item.description} onClick={()=>openExperiment(item)}><span className="experiment-icon"><Icon name={itemIcon(item)} size={27}/></span><span className="experiment-copy"><strong>{item.title}</strong><span>{item.loadError||item.description||t('打开实验查看操作界面与设备要求。','Open to view controls and equipment requirements.')}</span></span><span className="experiment-meta">{item.isLink?t('外部链接','External link'):inputLabel(item.requirements)}<small>{sourceLabel(item.source)}</small></span><Icon name="arrow" size={17}/></button>)}</div></section>)}</div>
    {!online&&<div className="empty"><h2>{t('正在连接本地服务…','Connecting to the local service…')}</h2><p>{t('请保持启动程序的终端窗口开启。','Keep the local service terminal open.')}</p></div>}{online&&!filtered.length&&<div className="empty"><Icon name="search" size={34}/><h2>{search?t('没有找到匹配的实验','No matching experiments'):t('这里还没有实验','No experiments here yet')}</h2><p>{search?t('换个关键词，或切换到全部实验。','Try another search or select all experiments.'):t('使用右上方“导入实验”添加 .phyphox 文件。','Import a .phyphox file using the button above.')}</p>{(search||source!=='all')&&<button onClick={()=>{setSearch('');setSource('all');}}>{t('显示全部实验','Show all experiments')}</button>}</div>}
    
   </>}
   {page==='storage'&&<StoragePanel snapshot={session} onSession={receiveSession} t={t}/>}
   <div hidden={page!=='media'} className="media-workspace"><p className="eyebrow">MEDIA DEVICES</p><h1>{t('麦克风、摄像头与扬声器','Microphone, camera & speaker')}</h1><p className="muted">{t('选择设备，启用后返回实验开始测量。','Choose and enable devices, then return to your experiment.')}</p><BrowserMediaPanel snapshot={session} onSession={receiveSession} t={t} onActivity={setMediaActivity}/><BrowserSpeakerPanel snapshot={session} onSession={receiveSession} t={t} onActivity={setSpeakerActive}/><details className="native-media-details"><summary>{t('高级：Windows 原生音频与相机接口','Advanced: Windows native audio & camera')}</summary><MediaPanel snapshot={session} onSession={receiveSession} t={t}/></details></div>
   {page==='devices'&&<DevicePanel initial={devices} snapshot={session} onSession={receiveSession} onLibraryChange={refreshLibrary} t={t}/>}
   {page==='experiment'&&(!session?.id?<div className="empty empty-experiment"><Icon name="wave" size={48}/><h1>{t('准备开始一次实验','Ready for an experiment')}</h1><p>{t('先从实验库中选择你想观察的现象。','Choose what you want to explore from the experiment library.')}</p><button className="primary" onClick={()=>navigate('library')}>{t('打开实验库','Open library')}<Icon name="arrow" size={16}/></button></div>:<>
    <div className="experiment-toolbar"><button className="icon-button back-button" aria-label={t('返回实验库','Back to experiments')} onClick={()=>navigate('library')}><Icon name="back"/></button><div className="experiment-title"><p>{current?.category||t('当前实验','Current experiment')}</p><h1>{session.title}</h1></div><div className="controls"><button className="primary measure-button" disabled={busy||!online||(!running&&!session.canStart)} onClick={()=>void command(running?'pause':'start')}><Icon name={running?'pause':'play'}/>{running?t('暂停','Pause'):status==='paused'?t('继续','Resume'):t('开始','Start')}</button><button className="icon-button" disabled={busy||!online} onClick={()=>{setClearGroups([]);setDialog('clear');}} title={t('清空数据','Clear data')} aria-label={t('清空数据','Clear data')}><Icon name="clear"/></button><button className="icon-button" disabled={busy||!online} onClick={()=>setDialog('save')} title={t('保存与导出','Save & export')} aria-label={t('保存与导出','Save & export')}><Icon name="save"/></button><button className="icon-button" onClick={()=>setDialog('about')} title={t('实验说明与更多操作','Experiment information & more')} aria-label={t('实验说明与更多操作','Experiment information & more')}><Icon name="more"/></button></div></div>
    <div className="measurement-status"><span className={'status-pill '+(running?'is-running':'')}>{running&&<i className="live-dot"/>}{statusLabel}</span><span className="elapsed">{Number(session.experimentTime||0).toFixed(2)} <small>s</small></span><span className="measurement-hint">{needsSetup?t('请完成下方配置。','Complete the setup below.'):running?t('实时更新中','Updating live'):status==='paused'?t('已保留数据，可继续测量','Data retained. Resume when ready.'):t('点击开始测量。','Press Start to measure.')}</span></div>
    {session.dataOrigin&&session.dataOrigin!=='experiment'&&<div className="alert provenance">{t('数据来自导入或恢复','Imported or restored data')}<details><summary>{t('来源','Source')}</summary>{session.dataOrigin}</details></div>}
    {setupIssues.length>0&&<div className="requirements-notice"><Icon name="device"/><div><strong>{t('开始前还需要','Setup needed')}</strong><ul className="requirements-list">{[...new Set(setupIssues.map(issue=>readableIssue(issue,session,t)))].map((issue,i)=><li key={i}>{issue}</li>)}</ul></div><div className="requirements-actions">{[...(session.inputs||[]),...(session.outputs||[])].some(i=>['audio','camera'].includes(i.type))&&<button onClick={()=>navigate('media')}>{t('设置音频与相机','Set up media')}<Icon name="arrow" size={15}/></button>}{session.inputs?.some(i=>!['audio','camera'].includes(i.type))&&<button onClick={()=>navigate('devices')}>{t('连接设备','Connect devices')}<Icon name="arrow" size={15}/></button>}</div></div>}

    {session.error&&<div role="alert" className="alert error">{session.error}</div>}
    <div className="tabs" role="tablist" aria-label={t('实验视图','Experiment views')}>{session.views.map((v,i)=><button key={i} id={`view-tab-${i}`} role="tab" aria-controls="experiment-view" aria-selected={tab===i} className={tab===i?'active':''} onClick={()=>setTab(i)}>{v.label}</button>)}</div><div className="view-elements" data-graph-count={session.views[tab]?.elements.filter(e=>e.type==='graph').length||0} id="experiment-view" role="tabpanel" aria-labelledby={`view-tab-${tab}`}>{session.views[tab]?.elements.map(el=><ViewElement key={session.id+el.id} element={el} snapshot={session} disabled={busy||!online} t={t} setValue={setValue} button={()=>void command('button',{elementId:el.id})}/>)}</div>
    <div className="experiment-bottom"><button className="text-button" onClick={()=>setDialog('about')}><Icon name="help" size={16}/>{t('实验说明','About this experiment')}</button><button className="text-button" onClick={()=>setDialog('save')}><Icon name="save" size={16}/>{t('保存结果','Save results')}</button></div>
   </>)}
   <footer><span>phyphox <b>Windows</b> · {t('移植开发版','Development port')}</span></footer>
  </main></div>
  {pending&&<Dialog title={t('切换实验','Switch experiment')} onClose={()=>{if(!busy)setPending(null);}}><p>{t(`将打开“${pending.title}”。当前实验的数据会被替换。`,`Opening “${pending.title}” will replace the current experiment data.`)}</p>{running?<><div className="alert">{t('当前仍在测量，请先暂停，再保存或切换。','Measurement is running. Pause before saving or switching.')}</div><div className="dialog-actions"><button onClick={()=>setPending(null)}>{t('继续当前实验','Keep measuring')}</button><button className="primary" disabled={busy} onClick={()=>void command('pause')}>{t('暂停测量','Pause measurement')}</button></div></>:<div className="dialog-actions"><button disabled={busy} onClick={()=>setPending(null)}>{t('取消','Cancel')}</button><button disabled={busy} onClick={()=>void load(pending)}>{t('直接切换','Switch without saving')}</button><button className="primary" disabled={busy} onClick={()=>void load(pending,true)}>{t('保存后切换','Save & switch')}</button></div>}{error&&<p role="alert" className="dialog-error">{error}</p>}</Dialog>}
  {dialog==='clear'&&<Dialog title={t('清空实验数据？','Clear experiment data?')} onClose={()=>{if(!busy)setDialog(null);}}><p>{t('将停止实验并清空所选数据，无法撤销。','This stops the experiment and clears the selected data. It cannot be undone.')}</p>{!!session?.clearGroups?.length&&<fieldset className="clear-group-options" disabled={busy}><legend>{t('另外清空以下分组（可多选）','Also clear these groups')}</legend><p className="muted">{t('普通数据容器始终清空。未选分组及受保护的数据会保留。','Ordinary buffers are always cleared. Unselected groups and protected data are retained.')}</p>{session.clearGroups.map(g=><label key={g}><input type="checkbox" checked={clearGroups.includes(g)} onChange={e=>setClearGroups(old=>e.target.checked?[...old,g]:old.filter(v=>v!==g))}/>{g}</label>)}</fieldset>}<div className="dialog-actions"><button disabled={busy} onClick={()=>setDialog(null)}>{t('取消','Cancel')}</button><button disabled={busy} onClick={()=>setDialog('save')}>{t('先保存','Save first')}</button><button className="danger" disabled={busy} onClick={async()=>{if(await command('clear',clearGroups.length?{groups:clearGroups}:{}))setDialog(null);}}>{t('确认清空','Clear data')}</button></div>{error&&<p role="alert" className="dialog-error">{error}</p>}</Dialog>}
  {dialog==='save'&&<Dialog title={t('保存与导出','Save & export')} onClose={()=>{if(!busy)setDialog(null);}}><p className="muted">{session?.title}</p>{running&&<div className="alert">{t('测量中：保存当前时点的数据。','Measuring: saves the data available now.')}</div>}<div className="save-options"><button disabled={busy||!online} onClick={()=>void saveLocal()}><Icon name="folder"/><span><strong>{t('保存到本机','Save locally')}</strong><small>{t('保存当前数据和状态，稍后从“数据与回放”恢复。','Keep data and state for later restoration in Data & replay.')}</small></span><Icon name="arrow" size={16}/></button><button disabled={busy||!online} onClick={()=>void download('state')}><Icon name="save"/><span><strong>{t('下载实验状态','Download experiment state')} <em>.phyphox</em></strong><small>{t('将实验定义与当前数据一起保存为文件。','Download the experiment definition with its current data.')}</small></span><Icon name="arrow" size={16}/></button><button disabled={busy||!online} onClick={()=>void download('csv')}><Icon name="save"/><span><strong>{t('导出数据表','Export data tables')} <em>CSV / ZIP</em></strong><small>{t('打包下载数据表，适合后续处理与分析。','Download data tables for further processing and analysis.')}</small></span><Icon name="arrow" size={16}/></button><button disabled={busy||!online} onClick={()=>void download('xlsx')}><Icon name="save"/><span><strong>{t('导出 Excel 工作簿','Export Excel workbook')} <em>.xlsx</em></strong><small>{t('使用 Excel 或其他兼容表格软件打开。','Open with Excel or another compatible spreadsheet app.')}</small></span><Icon name="arrow" size={16}/></button></div><p className="muted">{t('导出包含完整数据。','Exports include all data.')}</p>{error&&<p role="alert" className="dialog-error">{error}</p>}</Dialog>}
  {dialog==='about'&&<Dialog title={t('实验说明与操作','Experiment information')} onClose={()=>setDialog(null)}><h3>{session?.title}</h3><p className="experiment-description">{current?.description||t('此实验未提供文字说明。按照视图中的标签调整参数，点击开始进行测量。','No description provided. Use the view labels to adjust parameters, then press Start.')}</p><div className="about-meta"><span>{t('分类','Category')}</span><strong>{current?.category||'—'}</strong><span>{t('设备与输入输出','Equipment & I/O')}</span><strong>{inputLabel(current?.requirements||[])}</strong></div><button disabled={busy||!online} onClick={async()=>{if(await command('stop'))setDialog(null);}}>{t('停止实验','Stop experiment')}</button><details><summary>{t('运行与兼容性信息','Runtime & compatibility information')}</summary><p className="muted">.phyphox {current?.formatVersion||'—'} · {t('计算轮次','Analysis cycles')} {session?.cycle||0}</p><p className="muted">{t('打开文件不代表所有硬件与功能均受支持。开始前的检查会列出当前限制。','Opening a file does not imply full hardware and feature support. Preflight checks list current limitations.')}</p>{session?.displayLimit&&<p className="muted">{t(`图表显示每个容器最近 ${session.displayLimit.toLocaleString()} 项；保存和导出包含完整数据。`,`Charts show up to the latest ${session.displayLimit.toLocaleString()} values per buffer. Saves and exports include full data.`)}</p>}</details>{error&&<p role="alert" className="dialog-error">{error}</p>}</Dialog>}
  {dialog==='help'&&<Dialog title={t('开始你的第一个实验','Your first experiment')} onClose={()=>setDialog(null)}><ol className="help-steps"><li><strong>{t('选择实验','Choose an experiment')}</strong><p>{t('在实验库按分类浏览，或导入 .phyphox 文件。不熟悉时，可以先打开“公式计算工作台”。','Browse categories or import a .phyphox file. The formula workspace is a good place to learn the controls.')}</p></li><li><strong>{t('准备设备','Prepare your equipment')}</strong><p>{t('BLE、USB 在“连接设备”配置；麦克风、相机和扬声器在“音频与摄像头”启用。','Set up BLE and USB under Connect devices; enable media under Audio & camera.')}</p></li><li><strong>{t('开始测量，切换视图','Start and explore the views')}</strong><p>{t('点击开始，用分页查看数值、图表与参数。暂停会保留数据，再次开始可以继续。','Press Start and switch tabs to see values, charts, and controls. Pause retains data so you can resume.')}</p></li><li><strong>{t('保存结果','Save your results')}</strong><p>{t('使用实验右上方的保存按钮，保存到本机或导出文件。清空前会提示确认。','Use Save & export in the experiment toolbar. Save locally or download files. Clearing data requires confirmation.')}</p></li></ol><div className="dialog-actions"><button className="primary" onClick={()=>setDialog(null)}>{t('开始探索','Got it')}</button></div></Dialog>}
 </>;
}
function ViewElement({element:e,snapshot:s,disabled,t,setValue,button}:{element:Element;snapshot:Snapshot;disabled:boolean;t:(zh:string,en:string)=>string;setValue:(buffer:string,value:number)=>void;button:()=>void}){
 const a=e.attributes||{},input=e.inputs?.[0]?.buffer,output=e.outputs?.[0]?.buffer||input,value=(input||output)?s.buffers[input||output!]?.at(-1):null,numeric=value!==null&&value!==undefined?value:NaN;
 const maps=(e.children||[]).filter(n=>(n.name||n.type)==='map'),labelValue=a.dynamicLabel?s.buffers[a.dynamicLabel]?.at(-1):null;
 const mapped=labelValue!==null&&labelValue!==undefined?mappedText(labelValue,maps):undefined;
 const label=mapped||a.label||e.text||'',factor=Number(a.factor||1);
 const displayNumeric=e.type==='edit'?numeric*factor:numeric;
 const focused=useRef(false);
 const [draft,setDraft]=useState('');useEffect(()=>{if(!focused.current)setDraft(Number.isFinite(displayNumeric)?String(displayNumeric):'');},[displayNumeric]);
 const write=(v:string)=>{if(output&&v.trim()!==''&&Number.isFinite(Number(v))){if(e.type==='edit'&&Number(v)===displayNumeric)return;let n=Number(v);if(e.type==='edit'){if(a.decimal==='false')n=Math.round(n);if(a.signed==='false')n=Math.max(0,n);n=Math.max(Number(a.min??'-Infinity'),Math.min(Number(a.max??'Infinity'),n));n/=factor;}setValue(output,n);}};
 if(a.visibility&&!(Number(s.buffers[a.visibility]?.at(-1))>0))return null;
 if(e.type==='image')return <ExperimentImage id={s.id||''} src={a.src||''} label={label} scale={Number(a.scale||1)}/>;
 if(e.type==='separator')return <hr className="separator"/>;
 if(e.type==='info')return <section className="info" style={{textAlign:a.align as 'left'|'center'|'right',fontWeight:a.bold==='true'?'bold':undefined,fontStyle:a.italic==='true'?'italic':undefined,fontSize:`${Number(a.size||1)}em`,color:a.color}}><p>{label}</p></section>;
 if(e.type==='graph')return <section className="panel wide graph-panel"><Graph element={e} buffers={s.buffers} lengths={s.bufferLengths} updateKey={s.cycle} onPick={setValue}/></section>;
 if(e.type==='value'){const scale=Number(a.factor||1),precision=Math.max(0,Math.min(12,Number(a.precision||2)));return <section className="panel value"><label>{label}</label><div>{mappedText(numeric,maps)||(Number.isFinite(numeric)?(a.scientific==='true'?(numeric*scale).toExponential(precision):(numeric*scale).toFixed(precision)):'—')}<small>{a.unit}</small></div></section>;}
 if(e.type==='edit')return <section className="panel"><label htmlFor={e.id}>{label}</label><div className="row"><input id={e.id} type="number" value={draft} min={a.min} max={a.max} step="any" disabled={disabled||!output} onChange={v=>setDraft(v.target.value)} onFocus={()=>{focused.current=true;}} onBlur={()=>{focused.current=false;write(draft);}} onKeyDown={v=>{if(v.key==='Enter')v.currentTarget.blur();}}/><span>{a.unit}</span></div></section>;
 if(e.type==='button')return <section className="panel"><button className="primary" disabled={disabled} onClick={button}>{label||t('执行','Run')}</button></section>;
 if(e.type==='toggle')return <section className="panel"><label className="row"><input type="checkbox" checked={Number.isFinite(numeric)&&numeric===Number(a.valueOn||1)} disabled={disabled||!output} onChange={v=>output&&setValue(output,v.target.checked?Number(a.valueOn||1):Number(a.valueOff||0))}/>{label}</label></section>;
 if(e.type==='slider'&&a.type==='range')return <section className="panel"><label>{label}</label>{(e.outputs||[]).map(p=><RangeControl key={p.buffer} label={p.attributes.value==='upperValue'?t('上限','Upper'):t('下限','Lower')} value={s.buffers[p.buffer]?.at(-1)??Number(a.minValue||0)} min={a.minValue||'0'} max={a.maxValue||'100'} step={a.stepSize||'any'} disabled={disabled} onCommit={v=>setValue(p.buffer,v)}/>)}</section>;
 if(e.type==='slider')return <section className="panel"><label htmlFor={e.id}>{label} <strong>{draft||'—'} {a.unit}</strong></label><input id={e.id} type="range" min={a.minValue||0} max={a.maxValue||100} step={a.stepSize||'any'} value={draft||a.min||0} disabled={disabled||!output} onChange={v=>setDraft(v.target.value)} onPointerUp={()=>write(draft)} onKeyUp={()=>write(draft)}/></section>;
 if(e.type==='dropdown'){const options=maps;return <section className="panel"><label htmlFor={e.id}>{label}</label><select id={e.id} value={Number.isFinite(numeric)?String(numeric):''} disabled={disabled||!output} onChange={v=>write(v.target.value)}><option value="" disabled>—</option>{options.map((n,i)=><option key={i} value={n.attributes?.value||i}>{n.attributes?.label||n.text||i}</option>)}</select></section>;}
 return <section className="panel unsupported"><label>{label||e.type}</label><p>{t('暂不支持此视图。','This view is not supported yet.')}</p><code>{e.type}</code></section>;
}

function ExperimentImage({id,src,label,scale}:{id:string;src:string;label:string;scale:number}){
 const [url,setUrl]=useState(''),[error,setError]=useState('');
 useEffect(()=>{let active=true,objectUrl='';setError('');setUrl('');downloadBlob(`library/${encodeURIComponent(id)}/resource?src=${encodeURIComponent(src)}`).then(blob=>{objectUrl=URL.createObjectURL(blob);if(active)setUrl(objectUrl);else URL.revokeObjectURL(objectUrl);}).catch(e=>{if(active)setError(String(e));});return()=>{active=false;if(objectUrl)URL.revokeObjectURL(objectUrl);};},[id,src]);
 return <section className="panel">{url?<img alt={label||src} src={url} style={{maxWidth:'100%',width:`${Math.max(0,Math.min(1,scale))*100}%`}}/>:<p>{error||'…'}</p>}</section>;
}

function RangeControl({label,value,min,max,step,disabled,onCommit}:{label:string;value:number;min:string;max:string;step:string;disabled:boolean;onCommit:(value:number)=>void}){
 const [draft,setDraft]=useState(value),editing=useRef(false);
 useEffect(()=>{if(!editing.current)setDraft(value);},[value]);
 function commit(){editing.current=false;if(draft!==value)onCommit(draft);}
 return <label>{label} · {draft}<input type="range" value={draft} min={min} max={max} step={step} disabled={disabled} onPointerDown={()=>{editing.current=true;}} onKeyDown={()=>{editing.current=true;}} onChange={e=>setDraft(Number(e.target.value))} onPointerUp={commit} onKeyUp={commit} onBlur={()=>{if(editing.current)commit();}} onPointerCancel={()=>{editing.current=false;setDraft(value);}}/></label>;
}

function readableIssue(issue:string,session:Snapshot,t:(zh:string,en:string)=>string){
 if(issue.includes('Windows WASAPI')){
  const microphone=session.inputs?.some(i=>i.type==='audio'&&!session.browserMedia?.some(b=>b.inputIndex===i.index)),speaker=session.outputs?.some(i=>i.type==='audio'&&!session.browserAudioOutput?.some(b=>b.outputIndex===i.index));
  return microphone&&speaker?t('尚未启用麦克风和扬声器。','Enable a microphone and speaker.'):microphone?t('尚未启用麦克风。','Enable a microphone.'):t('尚未启用扬声器。','Enable a speaker.');
 }
 if(issue.includes('相机')&&issue.includes('Windows Media Foundation'))return t('尚未启用摄像头。','Enable a camera.');
 if(issue.includes('相机曝光模式需要'))return t('需要确认相机曝光设置。','Confirm the camera exposure settings.');
 if(issue.includes('曝光归一化亮度/光谱或物理曝光输出'))return t('此实验需要经过标定的固定曝光相机。','This experiment needs a calibrated camera with fixed exposure.');
 if(issue.includes('非循环音频的逐分析触发'))return t('此实验需要单次音频播放，当前尚不支持。','This experiment needs one-shot audio playback, which is not yet supported.');
 return issue;
}
