import {useEffect,useRef,useState} from 'react';
import {request,type Snapshot} from './api';
import './BrowserMediaPanel.css';
type Kind='audio'|'camera';
type Capture={epoch:number;owner:string;stream?:MediaStream;context?:AudioContext;source?:MediaStreamAudioSourceNode;worklet?:AudioWorkletNode;gain?:GainNode;timer?:ReturnType<typeof setTimeout>;captureId?:string;sequence:number;busy:boolean;sent:number;dropped:number;lastSent?:number;observed?:boolean};
type Meter={active:boolean;pending:boolean;sent:number;dropped:number;settings:string};
const blank=():Meter=>({active:false,pending:false,sent:0,dropped:0,settings:''});
type Props={embedded?:boolean;snapshot:Snapshot|null;onSession:(s:Snapshot)=>void;t:(zh:string,en:string)=>string;onActivity?:(info:{microphone:boolean;camera:boolean})=>void};
export default function BrowserMediaPanel({snapshot,onSession,t,onActivity,embedded=false}:Props){
 const [devices,setDevices]=useState<MediaDeviceInfo[]>([]),[listed,setListed]=useState(false),[listing,setListing]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('');
 const [audioDevice,setAudioDevice]=useState(''),[cameraDevice,setCameraDevice]=useState(''),[audioInput,setAudioInput]=useState(''),[cameraInput,setCameraInput]=useState('');
 const [width,setWidth]=useState('640'),[height,setHeight]=useState('480'),[fps,setFps]=useState('5');
 const [audio,setAudio]=useState<Meter>(blank),[camera,setCamera]=useState<Meter>(blank);
 const captures=useRef<Partial<Record<Kind,Capture>>>({}),epoch=useRef(0),video=useRef<HTMLVideoElement>(null),latest=useRef(snapshot),sessionCallback=useRef(onSession),activityCallback=useRef(onActivity),mounted=useRef(true);
 latest.current=snapshot;sessionCallback.current=onSession;activityCallback.current=onActivity;
 const setMeter=(kind:Kind,update:(m:Meter)=>Meter)=>{if(mounted.current)(kind==='audio'?setAudio:setCamera)(update);};
 function publishActivity(){activityCallback.current?.({microphone:!!captures.current.audio?.stream,camera:!!captures.current.camera?.stream});}
 function current(kind:Kind,c:Capture){return mounted.current&&captures.current[kind]===c&&latest.current?.id===c.owner;}
 function release(kind:Kind){const c=captures.current[kind];if(!c)return;delete captures.current[kind];if(c.timer)clearTimeout(c.timer);c.stream?.getTracks().forEach(track=>{track.onended=null;track.stop();});if(c.worklet){c.worklet.port.onmessage=null;c.worklet.disconnect();}c.source?.disconnect();c.gain?.disconnect();void c.context?.close().catch(()=>{});if(kind==='camera'&&video.current)video.current.srcObject=null;setMeter(kind,m=>({...m,active:false,pending:false}));publishActivity();return c;}
 async function stopAll(notify=true){const owner=latest.current?.id,all=Object.values(captures.current);release('audio');release('camera');const capture=all.find(c=>c?.captureId);if(notify&&capture?.captureId){try{const s=await request<Snapshot>('session/media/browser/stop',{sessionId:capture.owner,captureId:capture.captureId});if(mounted.current&&latest.current?.id===owner)sessionCallback.current(s);}catch(e){if(mounted.current&&latest.current?.id===owner)setError(String(e));}}}
 useEffect(()=>{mounted.current=true;const leave=()=>{void stopAll();};window.addEventListener('pagehide',leave);return()=>{mounted.current=false;window.removeEventListener('pagehide',leave);void stopAll();};},[]);
 useEffect(()=>{release('audio');release('camera');setAudioInput(snapshot?.inputs?.filter(i=>i.type==='audio').length===1?String(snapshot.inputs.find(i=>i.type==='audio')!.index):'');setCameraInput(snapshot?.inputs?.filter(i=>i.type==='camera').length===1?String(snapshot.inputs.find(i=>i.type==='camera')!.index):'');setError('');setNotice('');},[snapshot?.id]);
 useEffect(()=>{if(!snapshot?.browserMedia)return;for(const kind of ['audio','camera'] as const){const c=captures.current[kind];if(!c?.captureId)continue;if(snapshot.browserMedia.some(b=>b.captureId===c.captureId))c.observed=true;else if(c.observed)release(kind);}},[snapshot?.browserMedia]);
 const previousStatus=useRef(snapshot?.status);
 useEffect(()=>{if(previousStatus.current==='running'&&snapshot?.status!=='running'&&snapshot?.status!=='paused'){release('audio');release('camera');setNotice(t('已断开设备，需要测量时请重新连接。','Devices disconnected. Reconnect to measure again.'));}previousStatus.current=snapshot?.status;},[snapshot?.status]);
 async function enumerate(){setListing(true);setError('');try{if(!navigator.mediaDevices?.enumerateDevices)throw new Error(t('当前浏览器未提供设备枚举；请使用 localhost 或安全连接。','Device enumeration is unavailable; use localhost or a secure connection.'));setDevices(await navigator.mediaDevices.enumerateDevices());setListed(true);}catch(e){setError(e instanceof Error?e.message:String(e));}finally{setListing(false);}}
 async function fail(kind:Kind,c:Capture,e:unknown){if(!current(kind,c))return;setError(`${kind==='audio'?t('麦克风','Microphone'):t('相机','Camera')}: ${e instanceof Error?e.message:String(e)}`);await stopAll();}
 async function send(kind:Kind,c:Capture,payload:Record<string,unknown>){if(!current(kind,c)||!c.captureId)return;if(c.busy){if(kind==='audio'){void fail(kind,c,new Error(t('音频发送拥塞，为避免缺样造成错误时间轴已停止。','Audio transport congested; stopped to avoid a misleading timeline from missing samples.')));}else c.dropped++;return;}c.busy=true;try{const response=await request<{accepted?:boolean}>(kind==='audio'?'session/media/browser/audio':'session/media/browser/frame',{sessionId:c.owner,captureId:c.captureId,sequence:c.sequence++,...payload});if(current(kind,c)){if(response?.accepted===false){if(kind==='audio')throw new Error(t('服务未接受音频批次，已停止以避免缺样。','Service did not accept an audio batch; stopped to avoid missing samples.'));c.dropped++;}else c.sent++;c.lastSent=performance.now();setMeter(kind,m=>({...m,sent:c.sent,dropped:c.dropped}));}}catch(e){if(kind==='camera'&&(e as {status?:number}).status===429){c.dropped++;setMeter(kind,m=>({...m,dropped:c.dropped}));}else await fail(kind,c,(e as {status?:number}).status===429?new Error(t('音频服务拥塞，为避免缺样已停止。','Audio service congested; stopped to avoid missing samples.')):e);}finally{c.busy=false;}}
 async function start(kind:Kind){
  setError('');setNotice('');const owner=latest.current?.id,input=kind==='audio'?audioInput:cameraInput;
  if(!owner||input===''){setError(t('请选择实验输入。','Select an experiment input.'));return;}
  if(latest.current?.status==='running'){setError(t('请先停止实验，再准备浏览器来源。','Stop the experiment before preparing browser sources.'));return;}
  if(!window.isSecureContext||!navigator.mediaDevices?.getUserMedia){setError(t('浏览器采集需要 localhost 或 HTTPS，以及支持媒体授权的浏览器。','Browser capture requires localhost or HTTPS and media permission support.'));return;}
  const rate=Number(fps),w=Number(width),h=Number(height);
  if(kind==='camera'&&(!Number.isInteger(w)||w<1||w>1920||!Number.isInteger(h)||h<1||h>1080||!Number.isFinite(rate)||rate<1||rate>10)){setError(t('请填写宽 1–1920、高 1–1080、发送帧率 1–10。','Enter width 1–1920, height 1–1080 and upload frame rate 1–10.'));return;}
  const c:Capture={owner,epoch:++epoch.current,sequence:0,busy:false,sent:0,dropped:0};captures.current[kind]=c;setMeter(kind,()=>({...blank(),pending:true}));
  try{
   const id=kind==='audio'?audioDevice:cameraDevice;
   const stream=await navigator.mediaDevices.getUserMedia(kind==='audio'?{audio:{...(id?{deviceId:{exact:id}}:{}),channelCount:{ideal:1},echoCancellation:false,noiseSuppression:false,autoGainControl:false},video:false}:{audio:false,video:{...(id?{deviceId:{exact:id}}:{}),width:{ideal:w},height:{ideal:h},frameRate:{ideal:rate,max:10}}});
   if(!current(kind,c)){stream.getTracks().forEach(track=>track.stop());return;}c.stream=stream;publishActivity();
   const track=stream.getTracks()[0];track.onended=()=>void fail(kind,c,new Error(t('设备停止或权限被撤销。','Device ended or permission was revoked.')));
   let config:Record<string,unknown>={sessionId:owner,inputIndex:Number(input),kind};
   if(kind==='audio'){
    const context=new AudioContext();c.context=context;
    if(!context.audioWorklet)throw new Error(t('此浏览器不支持 AudioWorklet，请更换浏览器。','AudioWorklet is unavailable. Use a supported browser.'));
    await context.audioWorklet.addModule('/browser-pcm-worklet.js');
    if(!current(kind,c))return;await context.resume();if(context.state!=='running')throw new Error(t('音频处理未启动，请检查浏览器权限。','Audio processing did not start; check browser permissions.'));
    config={...config,sampleRate:context.sampleRate,channels:1};
   }else{
    const el=video.current;if(!el)throw new Error('Camera preview unavailable');el.srcObject=stream;await el.play();if(!current(kind,c))return;
    config={...config,width:el.videoWidth,height:el.videoHeight,spectrumAxis:'horizontal'};
   }
   const result=await request<{captureId:string;session:Snapshot;maximumFrameRate:number;timeoutSeconds:number}>('session/media/browser/configure',config);
   if(!current(kind,c)){void request('session/media/browser/stop',{sessionId:owner,captureId:result.captureId}).catch(()=>{});return;}
   c.captureId=result.captureId;sessionCallback.current(result.session);
   const settings=track.getSettings();setMeter(kind,m=>({...m,pending:false,active:true,settings:JSON.stringify({...settings,...(c.context?{processingSampleRate:c.context.sampleRate,transmittedChannels:1}:{} )},null,2)}));
   if(kind==='audio'){
    const context=c.context!;c.source=context.createMediaStreamSource(stream);c.worklet=new AudioWorkletNode(context,'phyphox-real-pcm',{numberOfInputs:1,numberOfOutputs:1,outputChannelCount:[1]});c.gain=context.createGain();c.gain.gain.value=0;
    c.worklet.port.onmessage=e=>{if(!current(kind,c))return;if(e.data.overrun){void fail(kind,c,new Error(t('浏览器音频队列未及时处理，已停止以避免缺样。','Browser audio queue was not handled in time; stopped to avoid missing samples.')));return;}if(c.busy){void fail(kind,c,new Error(t('音频发送速度不足，为避免缺样已停止。','Audio upload cannot keep up; stopped to avoid missing samples.')));return;}const {samples,sampleRate}=e.data as {samples:Float32Array;sampleRate:number};void send(kind,c,{sampleRate,samples:Array.from(samples)}).then(()=>{if(current(kind,c))c.worklet?.port.postMessage({ack:true});});};
    c.source.connect(c.worklet);c.worklet.connect(c.gain);c.gain.connect(context.destination);
   }else{
    const canvas=document.createElement('canvas');const context=canvas.getContext('2d');if(!context)throw new Error('Canvas unavailable');
    const frame=async()=>{if(!current(kind,c))return;const el=video.current;try{if(el&&el.readyState>=2){if(c.busy)c.dropped++;else{canvas.width=el.videoWidth;canvas.height=el.videoHeight;context.drawImage(el,0,0);const data=canvas.toDataURL('image/jpeg',.9);await send(kind,c,{width:canvas.width,height:canvas.height,mimeType:'image/jpeg',dataBase64:data.slice(data.indexOf(',')+1)});}}}catch(e){await fail(kind,c,e);}if(current(kind,c))c.timer=setTimeout(()=>void frame(),1000/Math.min(rate,result.maximumFrameRate));};void frame();
   }
   setNotice(t('已连接，请在实验页点击“开始”。','Connected. Start the experiment to measure.'));
   // Enumeration after explicit permission reveals labels without opening another device.
   void navigator.mediaDevices.enumerateDevices().then(items=>{if(current(kind,c)){setDevices(items);setListed(true);}}).catch(()=>{});
  }catch(e){await fail(kind,c,e);}
 }
 const inputs=(kind:Kind)=>(snapshot?.inputs??[]).filter(i=>i.type===kind);
 const locked=audio.pending||camera.pending;
 function deviceSelect(kind:Kind){const value=kind==='audio'?audioDevice:cameraDevice,set=kind==='audio'?setAudioDevice:setCameraDevice;return <label className="bm-field">{t('设备','Device')}<select value={value} onChange={e=>set(e.target.value)}><option value="">{t('系统默认','System default')}</option>{devices.filter(d=>d.kind===(kind==='audio'?'audioinput':'videoinput')).map((d,i)=><option key={d.deviceId||`${d.kind}-${i}`} value={d.deviceId} disabled={!d.deviceId}>{d.label||t(`未授权设备 ${i+1}`,`Device ${i+1} (permission needed)`)}</option>)}</select></label>;}
 function inputSelect(kind:Kind){return <label className="bm-field">{t('实验输入','Experiment input')}<select value={kind==='audio'?audioInput:cameraInput} onChange={e=>(kind==='audio'?setAudioInput:setCameraInput)(e.target.value)}><option value="">{t('请选择实验输入…','Select experiment input…')}</option>{inputs(kind).map(i=><option key={i.index} value={i.index}>{(i as typeof i & {name?:string}).name||t(`${kind==='audio'?'音频':'相机'}输入 ${i.index+1}`,`${kind==='audio'?'Audio':'Camera'} input ${i.index+1}`)}</option>)}</select>{!inputs(kind).length&&<small className="muted">{t('当前实验没有此类输入。','This experiment has no matching input.')}</small>}</label>;}
 const meter=(kind:Kind)=>{const m=kind==='audio'?audio:camera;return <><p className={m.active?'bm-live':'muted'} role="status">{m.pending?t('等待授权…','Waiting for permission…'):m.active?(snapshot?.status==='running'?t('采集中','Capturing'):t('已连接 · 待机','Connected · standby')):t('未连接','Disconnected')}</p><details><summary>{t('高级信息','Advanced information')}</summary><p className="muted bm-stats">{t('已接收批次','Received batches')}: {m.sent} · {t('跳过批次','Skipped batches')}: {m.dropped}</p>{m.settings&&<pre className="bm-settings">{m.settings}</pre>}<p className="muted">{kind==='audio'?t('单声道 PCM 使用 AudioContext 采样率。请求关闭回声消除、降噪和自动增益；浏览器及设备处理、幅值标定仍需核对。输入拥塞时停止采集。','Mono PCM uses the AudioContext sample rate. Echo cancellation, noise suppression and automatic gain are requested off. Browser/device processing and amplitude calibration require verification. Capture stops on congestion.'):t('服务处理 ROI，时间以接收时刻为准。相机可丢帧；JPEG 和浏览器颜色处理不适用于未经标定的物理亮度、曝光或光谱测量，不提供深度。','The service processes ROI and uses reception timestamps. Frames may be skipped. JPEG and browser color processing require calibration for physical brightness, exposure or spectrum measurements; depth is unavailable.')}</p></details></>;};
 return <section className="browser-media">{!embedded&&<h2>{t('麦克风与摄像头','Microphone & camera')}</h2>}{error&&<div className="alert error" role="alert">{error}</div>}{notice&&<p role="status">{notice}</p>}<div className="row"><button disabled={listing} onClick={()=>void enumerate()}>{listing?t('正在读取…','Reading…'):t('刷新设备','Refresh devices')}</button><button disabled={!audio.active&&!camera.active&&!locked} onClick={()=>void stopAll()}>{t('停止实验并断开设备','Stop experiment & disconnect')}</button></div>{listed&&!devices.length&&<p className="muted">{t('未找到设备，请检查连接和权限。','No devices found. Check connections and permissions.')}</p>}<div className="bm-grid">
 <section className="panel bm-card"><h2>{t('麦克风','Microphone')}</h2><fieldset disabled={audio.active||locked||snapshot?.status==='running'}>{deviceSelect('audio')}{inputSelect('audio')}<button className="primary" disabled={!snapshot?.id||audioInput===''} onClick={()=>void start('audio')}>{t('授权并连接麦克风','Connect microphone')}</button></fieldset>{meter('audio')}</section>
 <section className="panel bm-card"><h2>{t('摄像头','Camera')}</h2><fieldset disabled={camera.active||locked||snapshot?.status==='running'}>{deviceSelect('camera')}{inputSelect('camera')}<details><summary>{t('图像设置','Image settings')}</summary><div className="bm-fields"><label className="bm-field">{t('宽度','Width')}<input type="number" min={1} max={1920} value={width} onChange={e=>setWidth(e.target.value)}/></label><label className="bm-field">{t('高度','Height')}<input type="number" min={1} max={1080} value={height} onChange={e=>setHeight(e.target.value)}/></label><label className="bm-field">{t('帧率上限','FPS limit')}<input type="number" min={1} max={10} value={fps} onChange={e=>setFps(e.target.value)}/></label></div><p className="muted">{t('实际尺寸和帧率取决于设备。','Actual dimensions and frame rate depend on the device.')}</p></details><button className="primary" disabled={!snapshot?.id||cameraInput===''} onClick={()=>void start('camera')}>{t('授权并连接摄像头','Connect camera')}</button></fieldset><video ref={video} autoPlay playsInline muted aria-label={t('摄像头预览','Camera preview')} hidden={!camera.active&&!camera.pending}/>{meter('camera')}</section></div><details><summary>{t('连接说明','Connection information')}</summary><p className="muted">{t('授权后可显示设备名称。连接后在实验页开始测量；暂停保留连接，停止、清空或切换实验后需重新连接。请保持网页运行，后台节流或断网可能使测量停止。','Device names become available after permission. Start measurement from the experiment page. Pause keeps the connection; reconnect after stop, clear or switching experiments. Keep the page running; background throttling or disconnection may stop measurement.')}</p></details></section>;
}
