import {useEffect,useRef,useState} from 'react';
import type {Element,Port} from './api';
import {pairGraphInputs,barBounds,graphColors,paletteColor} from './graphData';
import {drawInterpolatedMap} from './mapRender';
type Point={x:number;y:number;index:number;z?:number};
const palette=['orange','green','blue','yellow','magenta','red'].map(c=>graphColors[c]);
function color(v:string|undefined,fallback:string){return v&&graphColors[v]?graphColors[v]:v&&CSS.supports('color',v)?v:v&&/^[0-9a-f]{6}$/i.test(v)?'#'+v:fallback;}
export default function Graph({element,buffers,lengths,updateKey,onPick}:{element:Element;buffers:Record<string,(number|null)[]>;lengths?:Record<string,number>;updateKey?:number;onPick:(buffer:string,value:number)=>void}){
 const canvas=useRef<HTMLCanvasElement>(null),box=useRef<HTMLDivElement>(null),a=element.attributes;
 const [range,setRange]=useState<[number,number]|null>(null),[pick,setPick]=useState<Point|null>(null),[selectedOutput,setSelectedOutput]=useState(0);
 const extent=useRef<[number,number]>([0,1]),drag=useRef<{x:number;range:[number,number]}|null>(null);
 useEffect(()=>{
  const target=canvas.current;if(!target)return;
  // React delegates wheel events passively; this listener must cancel page scrolling.
  const wheel=(event:WheelEvent)=>{
   event.preventDefault();
   const [lo,hi]=extent.current,scale=event.deltaY>0?1.2:.8;
   const fraction=Math.max(0,Math.min(1,(event.offsetX-58)/(target.clientWidth-74))),mid=lo+(hi-lo)*fraction;
   setRange([mid+(lo-mid)*scale,mid+(hi-mid)*scale]);
  };
  target.addEventListener('wheel',wheel,{passive:false});
  return()=>target.removeEventListener('wheel',wheel);
 },[]);
 const tx=(v:number)=>a.logX==='true'?Math.log10(v):v,ty=(v:number)=>a.logY==='true'?Math.log10(v):v;
 const series:{port:Port;x?:Port;points:Point[];style:string;color:string;lineWidth:number}[]=[];const styledX=new Set<Port>();
 const zport=element.inputs?.find(p=>p.attributes.axis==='z');
 for(const pair of pairGraphInputs(element.inputs||[])){const p=pair.y,currentX=pair.x,xa=currentX&&!styledX.has(currentX)?currentX.attributes:{};if(currentX)styledX.add(currentX);const attrs={...a,...xa,...p.attributes,...(zport?.attributes||{})};const xs=buffers[currentX?.buffer||'']||[],ys=buffers[p.buffer]||[],zs=buffers[zport?.buffer||'']||[];
 series.push({port:p,x:currentX,style:attrs.style||'lines',color:color(attrs.color,palette[series.length%palette.length]),lineWidth:Number(attrs.lineWidth||1),points:ys.map((v,i)=>({x:currentX?(xs[i]??NaN):Math.max(0,(lengths?.[p.buffer]??ys.length)-ys.length)+i,y:v??NaN,index:i,z:zs[i]??undefined}))});}
 const history=useRef<typeof series[]>([]),lastKey=useRef<string>(''),lastCycle=useRef<number>(-1),lastSeries=useRef<typeof series>([]);
 const requestedHistory=Math.max(1,Number(a.history||1)),historyCount=Math.min(32,requestedHistory);
 const stops:string[]=[];for(let i=1;a['mapColor'+i];i++)stops.push(color(a['mapColor'+i],'#000000'));if(!stops.length)stops.push('#000000',graphColors.orange,'#ffffff');
 const tz=(v:number)=>a.logZ==='true'?Math.log10(v):v;let mapMin=Infinity,mapMax=-Infinity;for(const s of series)for(const p of s.points)if(p.z!==undefined&&Number.isFinite(tz(p.z))){mapMin=Math.min(mapMin,tz(p.z));mapMax=Math.max(mapMax,tz(p.z));}if(a.scaleMinZ==='fixed')mapMin=tz(Number(a.minZ));if(a.scaleMaxZ==='fixed')mapMax=tz(Number(a.maxZ));
 const points=series.flatMap(s=>s.points).filter(p=>Number.isFinite(tx(p.x))&&Number.isFinite(ty(p.y)));
 useEffect(()=>{const key=JSON.stringify(series.map(s=>s.points));if((updateKey!==undefined&&updateKey<lastCycle.current)||!points.length){history.current=[];lastSeries.current=[];}if(key!==lastKey.current){if(lastSeries.current.length)history.current.unshift(lastSeries.current);history.current=history.current.slice(0,historyCount-1);lastSeries.current=series;lastKey.current=key;}lastCycle.current=updateKey??0;const c=canvas.current;if(!c)return;const draw=()=>{
 const dpr=window.devicePixelRatio||1,w=c.clientWidth,h=c.clientHeight;c.width=w*dpr;c.height=h*dpr;const ctx=c.getContext('2d')!;ctx.scale(dpr,dpr);const fg=getComputedStyle(c).color;
 ctx.clearRect(0,0,w,h);ctx.font='11px system-ui';ctx.fillStyle=fg;if(!points.length){ctx.fillText('—',w/2,h/2);return;}
 let lo=Infinity,hi=-Infinity,ymin=Infinity,ymax=-Infinity;for(const p of [...points,...history.current.flatMap(curves=>curves.flatMap(c=>c.points))].filter(p=>Number.isFinite(tx(p.x))&&Number.isFinite(ty(p.y)))){lo=Math.min(lo,tx(p.x));hi=Math.max(hi,tx(p.x));ymin=Math.min(ymin,ty(p.y));ymax=Math.max(ymax,ty(p.y));}
 if(series.some(s=>s.style==='vbars')&&a.logY!=='true'){ymin=Math.min(0,ymin);ymax=Math.max(0,ymax);}if(series.some(s=>s.style==='hbars')&&a.logX!=='true'){lo=Math.min(0,lo);hi=Math.max(0,hi);}
 const scale=(v:number,key:string,mode:string,min:boolean,transform:(x:number)=>number)=>{const n=transform(Number(a[key]));if(a[key]===undefined||!Number.isFinite(n))return v;return a[mode]==='fixed'?n:a[mode]==='extend'?(min?Math.min(v,n):Math.max(v,n)):v;};
 const latest=hi;lo=scale(lo,'minX','scaleMinX',true,tx);hi=scale(hi,'maxX','scaleMaxX',false,tx);ymin=scale(ymin,'minY','scaleMinY',true,ty);ymax=scale(ymax,'maxY','scaleMaxY',false,ty);
 if(a.followX==='true'&&a.logX!=='true'&&!range){lo=latest+Number(a.minX||-10);hi=latest+Number(a.maxX||0);}if(range)[lo,hi]=range;if(hi===lo)hi=lo+1;if(ymin===ymax){ymin-=.5;ymax+=.5;}extent.current=[lo,hi];
 const px=(v:number)=>58+(tx(v)-lo)/(hi-lo)*(w-74),py=(v:number)=>18+(ymax-ty(v))/(ymax-ymin)*(h-53);
 const format=(v:number,axis:'X'|'Y')=>{if(a['log'+axis]==='true')v=10**v;const precision=Number(a[axis.toLowerCase()+'Precision']??4);return a.suppressScientificNotation==='true'?v.toFixed(Math.min(10,Math.max(0,precision))):v.toPrecision(Math.min(12,Math.max(1,precision)));};
 ctx.strokeStyle=fg;for(let i=0;i<5;i++){const y=18+(h-53)*i/4;ctx.globalAlpha=.22;ctx.beginPath();ctx.moveTo(58,y);ctx.lineTo(w-16,y);ctx.stroke();ctx.globalAlpha=1;ctx.fillText(format(ymax-(ymax-ymin)*i/4,'Y'),2,y+4);}ctx.fillText(format(lo,'X'),58,h-13);ctx.fillText(format(hi,'X'),w-95,h-13);
 ctx.save();ctx.beginPath();ctx.rect(58,17,w-74,h-51);ctx.clip();
 const renderSeries=[...history.current.slice().reverse().flatMap((curves,i)=>curves.map(s=>({...s,opacity:.15+.45*(i+1)/(history.current.length+1)}))),...series.map(s=>({...s,opacity:1}))];
 for(const s of renderSeries){ctx.globalAlpha=s.opacity;ctx.strokeStyle=s.color;ctx.fillStyle=s.color;ctx.lineWidth=s.lineWidth;ctx.beginPath();let connected=false;
 const step=s.style==='lines'||s.style==='dots'?Math.max(1,Math.floor(s.points.length/(w*4))):1;const columns=Math.max(1,Math.floor(Number(a.mapWidth||1)));if(s.style==='map'&&a.interpolateMapColors!=='false'){drawInterpolatedMap(ctx,s.points,columns,px,py,tz,mapMin,mapMax,stops,w,h);continue;}
 for(let i=0;i<s.points.length;i+=step){const p=s.points[i];if(!Number.isFinite(tx(p.x))||!Number.isFinite(ty(p.y))){connected=false;continue;}const x=px(p.x),y=py(p.y);
 if(s.style==='dots'){ctx.moveTo(x+2,y);ctx.arc(x,y,2,0,Math.PI*2);}else if(s.style==='vbars'){const next=s.points[i+1];if(!next)continue;const [left,right]=barBounds(p.x,next.x,s.lineWidth),baseline=a.logY==='true'?h-35:py(0);ctx.fillRect(Math.min(px(left),px(right)),Math.min(y,baseline),Math.abs(px(right)-px(left)),Math.abs(baseline-y));}else if(s.style==='hbars'){const next=s.points[i+1];if(!next)continue;const [bottom,top]=barBounds(p.y,next.y,s.lineWidth),baseline=a.logX==='true'?58:px(0);ctx.fillRect(Math.min(x,baseline),Math.min(py(bottom),py(top)),Math.abs(baseline-x),Math.abs(py(top)-py(bottom)));}else if(s.style==='map'){if(p.z===undefined||!Number.isFinite(p.z))continue;if(!Number.isFinite(tz(p.z)))continue;ctx.fillStyle=`rgb(${paletteColor(stops,(tz(p.z)-mapMin)/(mapMax-mapMin||1)).join(',')})`;const neighborX=s.points[i%columns===columns-1?i-1:i+1],neighborY=s.points[i+columns]||s.points[i-columns];if(!neighborX||!neighborY)continue;const halfX=Math.abs(neighborX.x-p.x)/2,halfY=Math.abs(neighborY.y-p.y)/2;ctx.fillRect(px(p.x-halfX),py(p.y+halfY),px(p.x+halfX)-px(p.x-halfX),py(p.y-halfY)-py(p.y+halfY));}else{if(connected)ctx.lineTo(x,y);else ctx.moveTo(x,y);connected=true;}}
 if(s.style==='dots')ctx.fill();else if(s.style==='lines')ctx.stroke();}
 ctx.globalAlpha=1;if(pick){ctx.fillStyle='#ff913d';ctx.beginPath();ctx.arc(px(pick.x),py(pick.y),4,0,Math.PI*2);ctx.fill();}ctx.restore();
 };draw();const ro=new ResizeObserver(draw);ro.observe(c);return()=>ro.disconnect();},[buffers,range,pick,element]);
 return <div className="graph" ref={box}><div className="graph-actions"><span>{a.label||element.text}</span><button onClick={()=>setRange(null)} title="Reset view">↺</button><button title="Export PNG" onClick={()=>{const source=canvas.current;if(!source)return;const out=document.createElement('canvas'),dpr=window.devicePixelRatio||1;out.width=source.width;const hasLegend=series.some(s=>s.style==='map')&&a.showColorScale!=='false';out.height=source.height+(hasLegend?110:70)*dpr;const c=out.getContext('2d')!;c.fillStyle=getComputedStyle(box.current!).backgroundColor;c.fillRect(0,0,out.width,out.height);c.drawImage(source,0,35*dpr);c.scale(dpr,dpr);c.fillStyle=getComputedStyle(source).color;c.font='14px system-ui';c.fillText(a.label||'phyphox',16,23);c.font='11px system-ui';c.fillText(`${a.labelX||'x'} ${a.unitX||''} · ${a.labelY||'y'} ${a.unitY||''}`,16,out.height/dpr-12);if(hasLegend&&Number.isFinite(mapMin)){const gradient=c.createLinearGradient(80,0,out.width/dpr-80,0);stops.forEach((stop,i)=>gradient.addColorStop(stops.length===1?0:i/(stops.length-1),stop));c.fillStyle=gradient;c.fillRect(80,out.height/dpr-60,out.width/dpr-160,12);c.fillStyle=getComputedStyle(source).color;c.fillText(`${a.labelZ||'z'} ${a.unitZ||''} ${(a.logZ==='true'?10**mapMin:mapMin).toPrecision(4)} → ${(a.logZ==='true'?10**mapMax:mapMax).toPrecision(4)}`,80,out.height/dpr-30);}out.toBlob(blob=>{if(!blob)return;const url=URL.createObjectURL(blob),link=document.createElement('a');link.href=url;link.download=(a.label||'graph')+'.png';link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);});}}>PNG</button><button onClick={()=>box.current?.requestFullscreen()} title="Fullscreen">⛶</button></div><canvas ref={canvas} aria-label={a.label||'Graph'}
 onPointerDown={e=>{drag.current={x:e.clientX,range:extent.current};e.currentTarget.setPointerCapture(e.pointerId);}}
 onPointerMove={e=>{if(!drag.current)return;const d=drag.current,shift=(e.clientX-d.x)/(e.currentTarget.clientWidth-74)*(d.range[1]-d.range[0]);setRange([d.range[0]-shift,d.range[1]-shift]);}}
 onPointerUp={e=>{if(drag.current&&Math.abs(e.clientX-drag.current.x)<4&&points.length){const [lo,hi]=extent.current,target=lo+(e.nativeEvent.offsetX-58)/(e.currentTarget.clientWidth-74)*(hi-lo);const p=points.reduce((best,v)=>Math.abs(tx(v.x)-target)<Math.abs(tx(best.x)-target)?v:best);setPick(p);const output=(element.outputs||[]).filter(o=>o.attributes.axis==='x'||o.attributes.axis==='y')[selectedOutput];if(output)onPick(output.buffer,output.attributes.axis==='x'?p.x:p.y);}drag.current=null;}}/>
 {series.some(s=>s.style==='map')&&a.showColorScale!=='false'&&Number.isFinite(mapMin)&&<div className="map-legend"><span>{a.labelZ} {a.unitZ}</span><i style={{background:`linear-gradient(to right,${stops.join(',')})`}}/><span>{(a.logZ==='true'?10**mapMin:mapMin).toPrecision(4)} → {(a.logZ==='true'?10**mapMax:mapMax).toPrecision(4)}</span></div>}{historyCount>1&&<p className="graph-caption">History: {historyCount} · 浏览器收到的更新 / received view updates{requestedHistory>32?' · display limit 32':''}</p>}
 {(element.outputs||[]).length>0&&<div className="row graph-pickers"><select aria-label="Pick target" value={selectedOutput} onChange={e=>setSelectedOutput(Number(e.target.value))}>{(element.outputs||[]).filter(o=>o.attributes.axis==='x'||o.attributes.axis==='y').map((o,i)=><option value={i} key={i}>{o.attributes.label||o.buffer}</option>)}</select>{(element.outputs||[]).filter(o=>o.attributes.axis==='xcal'||o.attributes.axis==='ycal').map((o,i)=><label key={i}>{o.attributes.label||o.buffer}<input type="number" step="any" defaultValue={buffers[o.buffer]?.at(-1)??''} onBlur={e=>{if(e.target.value!==''&&Number.isFinite(Number(e.target.value)))onPick(o.buffer,Number(e.target.value));}}/></label>)}</div>}<div className="graph-caption">{a.labelX||series[0]?.x?.buffer||'index'} {a.unitX} · {a.labelY||series.map(s=>s.port.buffer).join(', ')} {a.unitY} {pick&&` | x=${pick.x.toPrecision(6)}  y=${pick.y.toPrecision(6)}`}</div></div>;
}
