import {useEffect,useRef,useState} from 'react';
import {downloadBlob,request,type Snapshot} from './api';
import './PanelForms.css';
type AudioDevice={id:string;name:string;isInput:boolean;isDefault:boolean};
type CameraDevice={index:number;name:string;width:number;height:number;reportedFramesPerSecond:number};
export default function MediaPanel({snapshot,onSession,t}:{snapshot:Snapshot|null;onSession:(s:Snapshot)=>void;t:(zh:string,en:string)=>string}){
 const [audio,setAudio]=useState<AudioDevice[]|null>(null),[cameras,setCameras]=useState<CameraDevice[]|null>(null),[maximum,setMaximum]=useState(1),[profile,setProfile]=useState('{}'),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState(''),[preview,setPreview]=useState(''),[advanced,setAdvanced]=useState(false),[advancedSeeded,setAdvancedSeeded]=useState(false),[cameraIndex,setCameraIndex]=useState(''),[width,setWidth]=useState(''),[height,setHeight]=useState(''),[fps,setFps]=useState(''),[axis,setAxis]=useState(''),[previewOwner,setPreviewOwner]=useState<string|undefined>();
 const latestSession=useRef(snapshot?.id),previewEpoch=useRef(0);if(latestSession.current!==snapshot?.id){latestSession.current=snapshot?.id;previewEpoch.current++;}
 function basicProfile(){return {index:cameraIndex.trim()===''?null:Number(cameraIndex),width:width.trim()===''?null:Number(width),height:height.trim()===''?null:Number(height),framesPerSecond:fps.trim()===''?null:Number(fps),spectrumAxis:axis};}
 useEffect(()=>()=>{if(preview)URL.revokeObjectURL(preview);},[preview]);
 useEffect(()=>{setPreview('');setPreviewOwner(undefined);setMessage('');},[snapshot?.id]);
 useEffect(()=>()=>{previewEpoch.current++;},[]);
 async function action(fn:()=>Promise<void>){setBusy(true);setError('');setMessage('');try{await fn();}catch(e){setError(e instanceof Error?e.message:String(e));}finally{setBusy(false);}}
 return <>{error&&<div className="alert error" role="alert">{error}</div>}{message&&<div className="alert">{message}</div>}
 <section className="panel storage-section"><h2>{t('音频设备','Audio devices')}</h2><button disabled={busy} onClick={()=>void action(async()=>setAudio((await request<{items:AudioDevice[]}>('media/audio/devices')).items))}>{t('读取音频设备列表','List audio devices')}</button><p>{t('原生音频使用系统默认设备。','Native audio uses the system default device.')}</p>{audio!==null&&(audio.length?<div className="recordings">{audio.map(d=><div className="recording" key={d.id}><div><strong>{d.name}</strong><small>{d.isInput?t('输入 / 麦克风','Input / microphone'):t('输出 / 扬声器','Output / speaker')} · {d.isDefault?t('系统默认','System default'):t('非默认','Not default')}</small><details><summary>{t('设备标识','Device identifier')}</summary><code>{d.id}</code></details></div></div>)}</div>:<p>{t('服务未返回可用音频设备。','No audio devices returned by the service.')}</p>)}</section>
 <section className="panel storage-section"><h2>{t('查找摄像头','Find cameras')}</h2><p>{t('探测时会短暂打开摄像头。','Probing briefly opens cameras.')}</p><div className="row"><label htmlFor="camera-maximum">{t('探测索引数量（1–8）','Number of indices (1–8)')}</label><input id="camera-maximum" type="number" min={1} max={8} value={maximum} onChange={e=>setMaximum(Number(e.target.value))}/><button disabled={busy||snapshot?.status==='running'||!Number.isInteger(maximum)||maximum<1||maximum>8} onClick={()=>void action(async()=>{const r=await request<{items:CameraDevice[];note:string}>('media/camera/probe',{maximumIndex:maximum});setCameras(r.items);setMessage(r.note);})}>{t('开始探测','Find cameras')}</button></div>{cameras!==null&&(cameras.length?<div className="recordings">{cameras.map(d=><div className="recording" key={d.index}><div><strong>{d.name}</strong><small>index {d.index} · {d.width}×{d.height} · {d.reportedFramesPerSecond} fps ({t('设备报告','device reported')})</small></div><button disabled={busy} onClick={()=>{setCameraIndex(String(d.index));setWidth(String(d.width));setHeight(String(d.height));setFps(d.reportedFramesPerSecond>0?String(d.reportedFramesPerSecond):'');setAdvanced(false);setMessage(t('已填入参数，请核对并选择光谱方向。','Parameters filled in. Review them and choose a spectrum direction.'));}}>{t('使用此设备','Use this device')}</button></div>)}</div>:<p>{t('探测未发现可用摄像头。','No available cameras were found.')}</p>)}</section>
 <section className="panel storage-section pf-form"><h2>{t('设置实验摄像头','Configure the experiment camera')}</h2><p>{t('选择探测结果，或手动填写参数。','Choose a detected device or enter its parameters.')}</p><p className="muted">{t('目标实验','Target experiment')}: {snapshot?.title||t('请先加载实验','Load an experiment first')}</p><label className="pf-check"><input type="checkbox" disabled={busy} checked={advanced} onChange={e=>{if(e.target.checked&&!advancedSeeded){setProfile(JSON.stringify(basicProfile(),null,2));setAdvancedSeeded(true);}setAdvanced(e.target.checked);}}/>{t('高级 JSON','Advanced JSON')}</label>
 {advanced?<div><p className="muted">{t('可配置设备控制、曝光物理参数和经过实测的验证标志。此模式提交下方完整JSON；切回表单仅提交基础配置，不附带高级值。设备曝光控制数值不能当作秒数。','Configure device controls, physical exposure metadata and verification flags backed by measurement. This mode submits the complete JSON below. Returning to the form submits basic fields only. Device exposure control values are not seconds.')}</p><button type="button" disabled={busy} onClick={()=>setProfile(JSON.stringify(basicProfile(),null,2))}>{t('用当前表单重新填充 JSON','Replace JSON with current form values')}</button><label htmlFor="camera-profile">{t('相机配置 JSON','Camera configuration JSON')}</label><textarea id="camera-profile" spellCheck={false} rows={12} value={profile} onChange={e=>setProfile(e.target.value)}/></div>:<fieldset disabled={busy} className="pf-fieldset"><legend>{t('基础采集参数','Basic acquisition parameters')}</legend><div className="pf-grid"><label className="pf-field">{t('摄像头索引','Camera index')}<input type="number" min="0" step="1" value={cameraIndex} placeholder={t('输入实际索引','Actual device index')} onChange={e=>setCameraIndex(e.target.value)}/></label><label className="pf-field">{t('图像宽度（像素）','Width (pixels)')}<input type="number" min="1" step="1" value={width} onChange={e=>setWidth(e.target.value)}/></label><label className="pf-field">{t('图像高度（像素）','Height (pixels)')}<input type="number" min="1" step="1" value={height} onChange={e=>setHeight(e.target.value)}/></label><label className="pf-field">{t('请求帧率（fps）','Requested frame rate (fps)')}<input type="number" min="0" step="any" value={fps} onChange={e=>setFps(e.target.value)}/></label><label className="pf-field">{t('光谱采样方向','Spectrum direction')}<select value={axis} onChange={e=>setAxis(e.target.value)}><option value="">{t('请选择…','Select…')}</option><option value="horizontal">{t('水平','Horizontal')}</option><option value="vertical">{t('垂直','Vertical')}</option></select></label></div><details><summary>{t('高级信息','Advanced information')}</summary><p className="muted">{t('实际尺寸和帧率取决于设备，换电脑后请重新核对索引。曝光、光谱与物理量需实测标定。','Actual dimensions and frame rate depend on the device. Check indices after changing computers. Exposure, spectrum and physical measurements require calibration.')}</p></details></fieldset>}
 <button className="primary" disabled={busy||!snapshot?.id||snapshot.status==='running'} onClick={()=>void action(async()=>{const p=advanced?JSON.parse(profile):basicProfile();if(!Number.isInteger(p.index)||p.index<0||!Number.isInteger(p.width)||p.width<=0||!Number.isInteger(p.height)||p.height<=0||!Number.isFinite(p.framesPerSecond)||p.framesPerSecond<=0)throw new Error(t('请填写摄像头索引、有效宽高和正帧率。','Enter a camera index, valid dimensions and positive frame rate.'));if(!['horizontal','vertical'].includes(p.spectrumAxis))throw new Error(t('请选择水平或垂直光谱方向。','Choose a horizontal or vertical spectrum direction.'));onSession(await request<Snapshot>('session/media/camera/configure',p));setMessage(t('已保存，请在实验页开始测量。','Saved. Start measurement from the experiment page.'));})}>{busy?t('正在保存…','Saving…'):t('保存配置','Save configuration')}</button>{snapshot?.status==='running'&&<p className="muted">{t('请先停止实验再修改摄像头配置。','Stop the experiment before changing camera configuration.')}</p>}</section>
 <section className="panel storage-section"><h2>{t('图像预览','Image preview')}</h2><p>{t('查看最近采集的图像。','View the latest captured image.')}</p><button disabled={busy} onClick={()=>void action(async()=>{const owner=latestSession.current,epoch=previewEpoch.current;setPreview('');try{const blob=await downloadBlob('session/media/camera/frame');if(epoch!==previewEpoch.current||owner!==latestSession.current)return;setPreviewOwner(owner);setPreview(URL.createObjectURL(blob));}catch(e){if(epoch===previewEpoch.current&&owner===latestSession.current)throw e;}})}>{t('刷新预览','Refresh preview')}</button>{preview&&previewOwner===snapshot?.id&&<img className="camera-preview" src={preview} alt={t('服务端实际采集帧','Actual service-acquired frame')}/>}</section>
 </>;
}
