import {useEffect,useState} from 'react';
import {request,type Element,type Snapshot} from './api';
import Graph from './Graph';
import {mappedText} from './viewData';
import './PanelForms.css';
type ImportRow={key:number;column:string;buffer:string;unit:string;scale:string;offset:string;waveSource:string};
const newImportRow=(key:number):ImportRow=>({key,column:'1',buffer:'',unit:'',scale:'1',offset:'0',waveSource:''});
type PendingImport={file:File;config:unknown;sessionId:string;title:string;buffers:string[]};
type Recording={id:string;complete:boolean;bytes:number;updatedAt:string;validation:string;source:string};
type SavedSnapshot={id:string;savedAt:string;title:string;bytes:number};
type Replay={recordingId:string;status:string;source:string;hardwareOutputEnabled:boolean;physicalMeasurement:boolean;displayLimit:number;bufferLengths:Record<string,number>;cycles:number;experimentTime:number;title:string;buffers:Snapshot['buffers'];views:Snapshot['views']};
export default function StoragePanel({snapshot,onSession,t}:{snapshot:Snapshot|null;onSession:(s:Snapshot)=>void;t:(zh:string,en:string)=>string}){
 const [recordings,setRecordings]=useState<Recording[]>([]),[error,setError]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[restoreId,setRestoreId]=useState(''),[file,setFile]=useState<File|null>(null),[options,setOptions]=useState('{\n  "delimited": {\n    "columns": []\n  },\n  "append": false,\n  "analyze": false\n}'),[replay,setReplay]=useState<Replay|null>(null),[tab,setTab]=useState(0),[snapshots,setSnapshots]=useState<SavedSnapshot[]>([]),[pendingRestore,setPendingRestore]=useState(''),[advanced,setAdvanced]=useState(false),[advancedSeeded,setAdvancedSeeded]=useState(false),[rows,setRows]=useState<ImportRow[]>([newImportRow(1)]),[delimiter,setDelimiter]=useState(','),[hasHeader,setHasHeader]=useState(true),[timeMode,setTimeMode]=useState('none'),[timeColumn,setTimeColumn]=useState(''),[sampleRate,setSampleRate]=useState(''),[timeBuffer,setTimeBuffer]=useState(''),[append,setAppend]=useState(false),[analyze,setAnalyze]=useState(false),[pendingImport,setPendingImport]=useState<PendingImport|null>(null);
 const buffers=Object.keys(snapshot?.buffers||{}),isWave=file?.name.toLowerCase().endsWith('.wav')===true,isTsv=file?.name.toLowerCase().endsWith('.tsv')===true;
 function updateRow(key:number,patch:Partial<ImportRow>){setRows(old=>old.map(r=>r.key===key?{...r,...patch}:r));}
 function basicOptions(validate=true){
 const targets=rows.map(r=>r.buffer);if(validate&&(!rows.length||targets.some(b=>!buffers.includes(b))||new Set(targets).size!==targets.length))throw new Error(t('请选择不重复的现有目标容器。','Select distinct existing target buffers.'));
 if(isWave){if(validate&&(rows.some(r=>!/^audio([1-9]|[12][0-9]|3[0-2])$|^time$/.test(r.waveSource))||new Set(rows.map(r=>r.waveSource)).size!==rows.length))throw new Error(t('请选择不重复的WAV通道或时间来源；服务会核对文件实际通道。','Select distinct WAV channels or time. The service verifies channels against the file.'));return {waveMappings:Object.fromEntries(rows.map(r=>[r.waveSource,r.buffer])),append,analyze};}
 const columns=rows.map(r=>({index:Number(r.column)-1,buffer:r.buffer,unit:r.unit.trim()||null,scale:Number(r.scale),offset:Number(r.offset)}));
 if(validate&&rows.some((r,i)=>r.column.trim()===''||!Number.isInteger(columns[i].index)||columns[i].index<0||r.scale.trim()===''||r.offset.trim()===''||!Number.isFinite(columns[i].scale)||!Number.isFinite(columns[i].offset)))throw new Error(t('列号需为大于等于1的整数，倍率与偏移需为有限数值。','Column numbers must be positive integers; scale and offset must be finite numbers.'));
 const timed=timeMode!=='none';if(validate&&timed&&(!buffers.includes(timeBuffer)||targets.includes(timeBuffer)))throw new Error(t('时间目标必须是独立于数据列的现有容器。','Time must map to an existing buffer distinct from data columns.'));
 if(validate&&timeMode==='column'&&(timeColumn.trim()===''||!Number.isInteger(Number(timeColumn))||Number(timeColumn)<1))throw new Error(t('请选择从1开始的有效时间列号。','Provide a positive, one-based time column number.'));
 if(validate&&timeMode==='rate'&&(sampleRate.trim()===''||!Number.isFinite(Number(sampleRate))||Number(sampleRate)<=0))throw new Error(t('请填写已知的正采样率，未知时选择不指定时间。','Provide a known positive sample rate, or choose unspecified time.'));
 return {delimited:{delimiter:isTsv?'\t':delimiter,hasHeader,columns,...(timeMode==='column'?{timeColumn:Number(timeColumn)-1}:{}),...(timeMode==='rate'?{sampleRate:Number(sampleRate)}:{}),...(timed?{timeBuffer}:{})},append,analyze};
 }
 async function refresh(){const [logs,shots]=await Promise.all([request<{items:Recording[]}>('recordings'),request<{items:SavedSnapshot[]}>('snapshots')]);setRecordings(logs.items);setSnapshots(shots.items);}
 useEffect(()=>{refresh().catch(e=>setError(String(e)));},[]);
 async function performImport(plan:PendingImport){if(snapshot?.id!==plan.sessionId||snapshot.status==='running')throw new Error(t('当前实验已变化或正在运行，请重新选择导入目标。','The target experiment changed or is running. Select the import target again.'));const form=new FormData();form.append('file',plan.file);form.append('optionsJSON',JSON.stringify(plan.config));const r=await request<{samples:number;timeSource:string;source:string;session:Snapshot}>('imports/data',form);onSession(r.session);setPendingImport(null);setMessage(t(`已导入 ${r.samples} 条样本 · ${r.source} · 时间来源：${r.timeSource}`,`Imported ${r.samples} samples · ${r.source} · time source: ${r.timeSource}`));}
 async function action(fn:()=>Promise<void>){setBusy(true);setError('');setMessage('');try{await fn();}catch(e){setError(e instanceof Error?e.message:String(e));}finally{setBusy(false);}}
 return <><p className="eyebrow">DATA & RECORDINGS</p><h1>{t('数据与回放','Data & replay')}</h1>{error&&<div className="alert error" role="alert">{error}</div>}{message&&<div className="alert">{message}</div>}
 <section className="panel storage-section"><h2>{t('保存的数据','Saved data')}</h2><p>{t('保存当前实验与数据，之后可继续使用。','Save the current experiment and data for later.')}</p><button disabled={busy||!snapshot?.id} onClick={()=>void action(async()=>{const r=await request<{id:string;saved:boolean}>('snapshots/save',{});if(!r.saved)throw new Error(t('服务未确认保存。','Save was not confirmed.'));setRestoreId(r.id);await refresh();setMessage(t('快照已保存。','Snapshot saved.'));})}>{t('保存当前快照','Save current snapshot')}</button><label htmlFor="restore-id">{t('选择已保存数据','Choose saved data')}</label><div className="row"><select id="restore-id" value={restoreId} onChange={e=>setRestoreId(e.target.value)}><option value="">{t('选择快照…','Select a snapshot…')}</option>{snapshots.map(item=><option key={item.id} value={item.id}>{item.title} · {new Date(item.savedAt).toLocaleString()}</option>)}</select><button disabled={busy||!restoreId.trim()} onClick={()=>setPendingRestore(restoreId)}>{t('恢复此快照…','Restore this snapshot…')}</button></div><button disabled={busy} onClick={()=>void action(refresh)}>{t('刷新列表','Refresh list')}</button>{restoreId&&<details><summary>{t('快照详情','Snapshot details')}</summary><code>{restoreId}</code></details>}{pendingRestore&&<div className="pf-confirm" role="alertdialog" aria-labelledby="restore-confirm-title"><h3 id="restore-confirm-title">{t('确认覆盖当前实验数据？','Replace the current experiment data?')}</h3><p>{t(`将恢复快照「${snapshots.find(item=>item.id===pendingRestore)?.title||pendingRestore}」，替换「${snapshot?.title||'当前会话'}」的容器与参数。正在运行的实验会停止，未保存的当前数据将被覆盖，设备连接不会恢复。`,`Restore snapshot “${snapshots.find(item=>item.id===pendingRestore)?.title||pendingRestore}” and replace the current buffers and parameters. A running experiment will stop, unsaved current data will be overwritten, and device connections will not be restored.`)}</p><div className="row"><button autoFocus disabled={busy} onClick={()=>setPendingRestore('')}>{t('取消','Cancel')}</button><button className="primary" disabled={busy} onClick={()=>void action(async()=>{const id=pendingRestore;onSession(await request<Snapshot>(`snapshots/${encodeURIComponent(id)}/restore`,{}));setPendingRestore('');setMessage(t('快照已恢复。','Snapshot restored.'));await refresh();})}>{t('确认恢复并覆盖','Restore and replace')}</button></div></div>}</section>
 <section className="panel storage-section pf-form"><h2>{t('导入已有数据','Import recorded data')}</h2><p className="muted">{t('目标实验','Target experiment')}: <strong>{snapshot?.title||t('请先加载实验','Load an experiment first')}</strong></p><label className="pf-field">{t('1. 选择 CSV、TSV 或 WAV 文件','1. Choose a CSV, TSV or WAV file')}<input type="file" accept=".csv,.tsv,.wav" disabled={busy} onChange={e=>{setFile(e.target.files?.[0]||null);setError('');}}/></label>{file&&<p className="pf-file-note">{file.name} · {(file.size/1024).toFixed(1)} KiB</p>}
 <label className="pf-check"><input type="checkbox" checked={advanced} disabled={busy} onChange={e=>{if(e.target.checked&&!advancedSeeded){setOptions(JSON.stringify(basicOptions(false),null,2));setAdvancedSeeded(true);}setAdvanced(e.target.checked);}}/>{t('使用高级 JSON 配置','Use advanced JSON configuration')}</label>
 {advanced?<div><p className="muted">{t('当前按下方 JSON 提交；切回表单将使用表单中的值。JSON 中列索引从0开始。','The JSON below is submitted in this mode. Returning to the form uses its values. JSON column indices start at zero.')}</p><button type="button" disabled={busy} onClick={()=>setOptions(JSON.stringify(basicOptions(false),null,2))}>{t('用当前表单重新填充 JSON','Replace JSON with current form values')}</button><label htmlFor="data-options">{t('数据映射 JSON','Data mapping JSON')}</label><textarea id="data-options" rows={12} spellCheck={false} value={options} onChange={e=>setOptions(e.target.value)}/></div>:<fieldset disabled={busy} className="pf-fieldset"><legend>{t('2. 设置数据对应关系','2. Map data to experiment buffers')}</legend>{!isWave&&<div className="pf-grid"><label className="pf-field">{t('分隔符','Delimiter')}<select value={isTsv?'\t':delimiter} disabled={isTsv} onChange={e=>setDelimiter(e.target.value)}><option value=",">{t('逗号 ,','Comma ,')}</option><option value=";">{t('分号 ;','Semicolon ;')}</option><option value={'\t'}>{t('制表符 Tab','Tab')}</option></select></label><label className="pf-check"><input type="checkbox" checked={hasHeader} onChange={e=>setHasHeader(e.target.checked)}/>{t('首行为列名，不导入','First row is a header')}</label></div>}
 <p className="muted">{isWave?t('WAV 使用文件采样率，请选择要导入的通道。','WAV uses its recorded sample rate. Select the channels to import.'):t('表单列号从1开始。换算后的数值 = 原始值 × 倍率 + 偏移；未知单位可以留空。','Form column numbers start at one. Converted value = input × scale + offset. Leave unknown units blank.')}</p>
 {rows.map((r,i)=><div className="pf-mapping" key={r.key}><div className="pf-mapping-title"><strong>{t('映射','Mapping')} {i+1}</strong><button type="button" disabled={rows.length===1} onClick={()=>setRows(old=>old.filter(v=>v.key!==r.key))}>{t('移除','Remove')}</button></div><div className="pf-grid">{isWave?<label className="pf-field">{t('WAV 来源','WAV source')}<select value={r.waveSource} onChange={e=>updateRow(r.key,{waveSource:e.target.value})}><option value="">{t('选择通道…','Choose channel…')}</option>{Array.from({length:32},(_,c)=><option key={c} value={`audio${c+1}`}>{t('通道','Channel')} {c+1}</option>)}<option value="time">{t('文件时间轴（秒）','File time axis (seconds)')}</option></select></label>:<label className="pf-field">{t('文件列号','File column')}<input type="number" min="1" step="1" value={r.column} onChange={e=>updateRow(r.key,{column:e.target.value})}/></label>}<label className="pf-field">{t('写入实验容器','Target buffer')}<select value={r.buffer} onChange={e=>updateRow(r.key,{buffer:e.target.value})}><option value="">{t('选择容器…','Choose buffer…')}</option>{buffers.map(b=><option key={b}>{b}</option>)}</select></label>{!isWave&&<><label className="pf-field">{t('单位（可选）','Unit (optional)')}<input value={r.unit} onChange={e=>updateRow(r.key,{unit:e.target.value})}/></label><label className="pf-field">{t('倍率','Scale')}<input type="number" step="any" value={r.scale} onChange={e=>updateRow(r.key,{scale:e.target.value})}/></label><label className="pf-field">{t('偏移','Offset')}<input type="number" step="any" value={r.offset} onChange={e=>updateRow(r.key,{offset:e.target.value})}/></label></>}</div></div>)}<button type="button" onClick={()=>setRows(old=>[...old,newImportRow(Math.max(...old.map(r=>r.key))+1)])}>{t('+ 添加映射','+ Add mapping')}</button>
 {!isWave&&<div className="pf-time"><h3>{t('时间来源','Time source')}</h3><div className="pf-grid"><label className="pf-field">{t('时间如何确定','How is time determined?')}<select value={timeMode} onChange={e=>setTimeMode(e.target.value)}><option value="none">{t('不指定时间','Unspecified')}</option><option value="column">{t('文件中的时间列（秒）','Time column in seconds')}</option><option value="rate">{t('已知采样率','Known sample rate')}</option></select></label>{timeMode==='column'&&<label className="pf-field">{t('时间列号（从1开始）','Time column (one-based)')}<input type="number" min="1" step="1" value={timeColumn} onChange={e=>setTimeColumn(e.target.value)}/></label>}{timeMode==='rate'&&<label className="pf-field">{t('采样率（Hz）','Sample rate (Hz)')}<input type="number" min="0" step="any" value={sampleRate} onChange={e=>setSampleRate(e.target.value)}/></label>}{timeMode!=='none'&&<label className="pf-field">{t('时间目标容器','Time buffer')}<select value={timeBuffer} onChange={e=>setTimeBuffer(e.target.value)}><option value="">{t('选择独立时间容器…','Choose a separate time buffer…')}</option>{buffers.map(b=><option key={b}>{b}</option>)}</select></label>}</div></div>}
 <div className="pf-grid pf-submit-options"><label className="pf-field">{t('写入方式','Write mode')}<select value={append?'append':'replace'} onChange={e=>setAppend(e.target.value==='append')}><option value="replace">{t('替换映射容器中的数据','Replace mapped buffers')}</option><option value="append">{t('追加到映射容器末尾','Append to mapped buffers')}</option></select></label><label className="pf-check"><input type="checkbox" checked={analyze} onChange={e=>setAnalyze(e.target.checked)}/>{t('导入后执行一次分析','Run analysis once after import')}</label></div></fieldset>}
 <p className="muted">{t('需要保留当前结果时，请先保存快照。','Save a snapshot first to keep your current results.')}</p><button className="primary" disabled={busy||!file||!snapshot?.id||snapshot.status==='running'} onClick={()=>void action(async()=>{const config=advanced?JSON.parse(options):basicOptions();if(isWave?!Object.keys(config.waveMappings||{}).length:!config.delimited?.columns?.length)throw new Error(t('请填写明确的通道或列映射。','Provide explicit channel or column mappings.'));const targets:string[]=isWave?Object.values(config.waveMappings):config.delimited.columns.map((c:{buffer:string})=>c.buffer);if(!isWave&&(config.delimited.timeColumn!=null||config.delimited.sampleRate!=null))targets.push(config.delimited.timeBuffer||'time');const plan:PendingImport={file:file!,config,sessionId:snapshot!.id!,title:snapshot!.title,buffers:[...new Set(targets)]};if(config.append!==true&&targets.some(b=>(snapshot?.bufferLengths?.[b]??snapshot?.buffers[b]?.length??0)>0)){setPendingImport(plan);return;}await performImport(plan);})}>{busy?t('正在处理…','Working…'):t('导入到当前实验','Import into current experiment')}</button>{snapshot?.status==='running'&&<p className="muted">{t('请先停止实验再导入数据。','Stop the experiment before importing data.')}</p>}{pendingImport&&<div className="pf-confirm" role="alertdialog" aria-labelledby="import-confirm-title"><h3 id="import-confirm-title">{t('确认覆盖已有容器数据？','Replace existing buffer data?')}</h3><p>{t(`将把「${pendingImport.file.name}」导入实验「${pendingImport.title}」，覆盖以下映射容器中的已有数据：`,`Import “${pendingImport.file.name}” into “${pendingImport.title}” and replace existing data in these mapped buffers:`)}</p><p className="buffer-names"><strong>{pendingImport.buffers.join(', ')}</strong></p><p className="muted">{t('需要保留当前结果时，请先取消并保存快照。','Cancel and save a snapshot first to keep your current results.')}</p><div className="row"><button autoFocus disabled={busy} onClick={()=>setPendingImport(null)}>{t('取消导入','Cancel import')}</button><button className="primary" disabled={busy||snapshot?.status==='running'} onClick={()=>void action(()=>performImport(pendingImport))}>{t('确认覆盖并导入','Replace and import')}</button></div></div>}</section>
 <section className="panel storage-section"><div className="row"><h2>{t('实验记录','Experiment recordings')}</h2><button disabled={busy} onClick={()=>void action(refresh)}>{t('刷新记录','Refresh recordings')}</button></div><p>{t('完整记录可重新计算并查看。','Recompute and view complete recordings.')}</p>{!recordings.length?<p>{t('暂无记录。运行并停止实验后刷新。','No recordings. Run and stop an experiment, then refresh.')}</p>:<div className="recordings">{recordings.map(r=><div className="recording" key={r.id}><div><strong>{new Date(r.updatedAt).toLocaleString()}</strong><details><summary>{t('记录详情','Recording details')}</summary><code>{r.id}</code><p>{r.source} · {r.validation}</p></details><small>{(r.bytes/1024).toFixed(1)} KiB · {r.complete?t('完整日志','Complete journal'):t('不完整或录制中','Incomplete or active')}</small></div><button disabled={busy||!r.complete} onClick={()=>void action(async()=>{const result=await request<Replay>(`recordings/${encodeURIComponent(r.id)}/replay`,{});if(result.hardwareOutputEnabled!==false)throw new Error(t('回放没有确认设备输出关闭，已拒绝展示。','Replay did not confirm disabled hardware outputs.'));setReplay(result);setTab(0);})}>{t('重新计算并查看','Recompute & view')}</button></div>)}</div>}</section>
 {replay&&<section className="replay-results"><div className="page-heading"><div><p className="eyebrow">RECORDED INPUT RECOMPUTATION</p><h2>{replay.title}</h2><p className="muted">{t('回放结果','Replay result')} · {replay.experimentTime.toFixed(3)} s</p></div><button onClick={()=>setReplay(null)}>{t('关闭回放结果','Close replay results')}</button></div><div className="tabs" role="tablist">{replay.views.map((v,i)=><button key={i} role="tab" aria-selected={tab===i} className={tab===i?'active':''} onClick={()=>setTab(i)}>{v.label}</button>)}</div><div className="view-elements">{replay.views[tab]?.elements.map(e=><ReplayElement key={e.id} element={e} result={replay}/>)}</div><details><summary>{t('高级：数据详情','Advanced: data details')}</summary><p>{replay.recordingId} · {replay.source} · {replay.cycles} {t('轮计算','cycles')}</p><p>{t(`每个容器显示最近 ${replay.displayLimit} 项。回放不驱动设备。`,`Showing the latest ${replay.displayLimit} values per buffer. Replay does not drive devices.`)}</p><div className="buffer-table">{Object.entries(replay.buffers).map(([name,values])=><div key={name}><code>{name}</code><span>{replay.bufferLengths[name]}</span><strong>{values.at(-1)??'—'}</strong></div>)}</div></details></section>}
 </>;
}
function ReplayElement({element:e,result:r}:{element:Element;result:Replay}){const a=e.attributes||{},name=e.inputs?.[0]?.buffer||e.outputs?.[0]?.buffer,value=r.buffers[name]?.at(-1);if(a.visibility&&!(Number(r.buffers[a.visibility]?.at(-1))>0))return null;if(e.type==='graph')return <section className="panel wide"><Graph element={{...e,outputs:[]}} buffers={r.buffers} lengths={r.bufferLengths} onPick={()=>{}}/></section>;if(e.type==='separator')return <hr className="separator"/>;if(e.type==='info')return <div className="info">{a.label||e.text}</div>;if(e.type==='button'||e.type==='image'||e.type.endsWith('-gui'))return null;return <section className="panel value"><label>{a.label||name||e.type}</label><div>{mappedText(value??NaN,(e.children||[]).filter(n=>(n.name||n.type)==='map'))||(typeof value==='number'&&Number.isFinite(value)?(value*Number(a.factor||1)).toFixed(Math.max(0,Math.min(10,Number(a.precision||3)))):'—')}<small>{a.unit}</small></div></section>;}
